### ISSUE TITLE
Game crash when attempting to insert 2 tank upgrades with shift click

### ISSUE THREAD

**Issue by Bablela26** [P3pp3rF1y/SophisticatedBackpacks#1021]
The game crashes when attempting to insert 2 tank upgrades with shift click,
like that :
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/80642972/a831b245-4d4a-4ffb-9a37-fd00aba65474)

crash log :
[crash-2024-04-02_17.28.24-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/14839477/crash-2024-04-02_17.28.24-client.txt)

**Comment by P3pp3rF1y** [comment]
That's some anti ad mod crashing you no idea what that is but there isn't even SB in that crash log.

**Comment by Bablela26** [comment]
Oh you mean InventoryProfilesNext, I'll report it to them then. Although I'm pretty sure someone else who doesn't use IPN has said it happened to them. So when you try it does it work?

**Comment by P3pp3rF1y** [comment]
Yup works like a charm for me. I haven't realized that IPN is in anti_ad package but yeah please report to them as there's something odd going on there in their code it seems that it happens even before SB has a chance to do anything or it happens after SB logic but in completely separate processing because I don't see SB in that crash log's stack trace.

**Comment by P3pp3rF1y** [comment]
closing as this is on IPN side
