### ISSUE TITLE
Magnet upgrade not working with certain items from AE2

### ISSUE THREAD

**Issue by Kafuruu** [P3pp3rF1y/SophisticatedBackpacks#1050]
I was playing Create: Above and Beyond 1.18 version and the magnet upgrade did not pickup items from AE2: ender dust, quantum entangled singularity, singularity. The magnet upgrade works with any other item but for some reason those 3 items only get picked up when it touches the backpack. 
Although its not very important I am curious why the magnet stops working

Place backpack with magnet upgrade
Throw the any of the 3 mentioned items near the backpack
Backpack does not pickup item within its radius unless the item touches it

Expected behavior
The backpack should pickup these items

[video](https://imgur.com/HEH8T4r)

Versions
Tested in a world with only
appliedenergistics2-forge-11.7.6
sophisticatedbackpacks-1.18.2-3.20.2.1036
sophisticatedcore-1.18.2-0.6.4.604

**Comment by P3pp3rF1y** [comment]
The reason is that those items are special item entities, they no longer use that in 1.20 for AE.

I no longer support 1.18 with anything but critical fixes so given that this is the first time I am hearing about any item having this issue and it's no longer a problem in 1.20 I am going to close. May add support for custom item entities in the future if I hear about any in newer versions, but definitely not adding that in 1.18.
