### ISSUE TITLE
Config not working within minecraft?

### ISSUE THREAD

**Issue by SestyZex** [P3pp3rF1y/SophisticatedBackpacks#1056]
I can't seem to change any configs within Minecraft to fix only having one smelter at a time in a backpack's upgrade slot. I want to have an auto smelter and auto smoker, but the options for configuring the mod are greyed out, everything is up to date. Did you remove the option in a later patch or is there a way I can configure that in another file? and if so how? I am running on Forge 47.2.0 on AT launcher.
If you need any more information feel free to ask.

**Comment by P3pp3rF1y** [comment]
You are using some mod for the configuration gui (I am guessing configured) because there's no gui included by default with forge and I am not adding any either. So you will need to direct this question to them. I have no idea what are the conditions for the gui to be configurable vs not and what I could have done to make it disappear (and I don't recall making any real changes to config other than maybe adding one or two options recently).

And configs as always can be changed in configuration files (`sophisticatedbackpacks-server.toml` for your case)

**Comment by SestyZex** [comment]
I looked in that file multiple times, and I still don't see anywhere I can change the limit of smelter upgrades on a backpack. On a previous versions I had no issues, but now, when I try and make a new backpack, it says the limit of smelters is one. The only configurations I found for the mod were changing the vanilla loot tables and enabling/disabling their crafting recipes.

**Comment by P3pp3rF1y** [comment]
sounds like you are not looking into server configs but common ones. Search for that file name I shared above and there's `maxUpgradesPerStorage` in there

**Comment by SestyZex** [comment]
I used Everything file Explorer to look for the file, it didn't occur to me to look in my /Game/saves instead of /Game/config. But I did get it all fixed and I will see if I can remove the GUI mod that blocks it. Thanks for you help 👍
