### ISSUE TITLE
1.20 - Fluid in backpack that no longer exists in modpack crashes it on open

### ISSUE THREAD

**Issue by Flexico** [P3pp3rF1y/SophisticatedBackpacks#1063]
Crash log: https://www.mediafire.com/file/suedvpzgk48pxoe/2024-05-28_Backpack_latest.log/file

I'm trying to update my world from 1.18.2 to 1.20.1, and even though I mostly have the same mods installed, when I open my main backpack, the game freezes and crashes. I've tried placing it on a hopper to pull out the items and backpacks inside it, but it actually starts pulling out items from within the inner backpacks, which is problematic because I have several millions of blocks and ores in some of them.

Has something changed in the newer version of the mod? As in, how the contents are encoded or something? Or am I doing something silly that has a simple obvious solution? XD

UPDATE: I notice that there is now a limit on how many stack upgrades can be placed in each backpack, which is an item I abused quite heavily in the past -- could an excess of stack upgrades in the backpacks in question cause this?

**Comment by P3pp3rF1y** [comment]
Could you share that crash log on some normal site like pastebin / hastebin / github gist? I don't really want to go through ads to be able to get to crash log

As for stack upgrades causing this alone that's unlikely as I made that change midway through the multiple major releases, made sure it allows players to continue using them in backpacks if they already have the stack upgrades in there and haven't had any report on that not working in months since the change was made.

**Comment by Flexico** [comment]
Oh dang, there's ads? I tried to post it to Pastebin, but it's too big. Hastebin doesn't like it either. Oh! I forgot I could just add the file here. XD
[2024-05-28_Backpack_latest.log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/15470505/2024-05-28_Backpack_latest.log)

**Comment by P3pp3rF1y** [comment]
Looks like you had a fluid in that backpack that doesn't exist anymore in your new pack. I should probably add a bit of a check to prevent this from crashing but it will take me a bit of time to add so likely best to transfer stuff from backpack using pipes (and yes that means you won't get upgrades) or try to add the fluid into your pack

**Comment by Flexico** [comment]
Ah, thank you! What fluid is it?

**Comment by P3pp3rF1y** [comment]
I have no idea it's just clear from the exception it can't be found in fluid registry. Definitely some modded fluid

**Comment by Flexico** [comment]
Found it; it was seed oil haha

**Comment by Flexico** [comment]
Ok, I deleted the tank upgrades with the errored fluids, but it still crashes!
[latest.log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/15477360/latest.log)

**Comment by P3pp3rF1y** [comment]
That's because the fluid reference is also stored separately in render nbt (that's something that actually gets regularly synced to client vs the full contents that mostly exist only on server and only necessary stuff gets synced to client). You would want to remove that tank in the previous version of the pack before you try to load it in 1.20. 
Also please upload crash logs instead of the full latest.log, much easier to immediately look at the actual crash instead of having to scroll down and look it up from there.

**Comment by Flexico** [comment]
Ah, ok. I had to remove the tank upgrades, then place the backpack and pick it back up. Things are working now, yay! =D

**Comment by P3pp3rF1y** [comment]
This is fixed in 1.21, I don't feel it's critical enough to warrant fixes in previous versions.
