### ISSUE TITLE
EXP stored on backpack crashes after death 

### ISSUE THREAD

**Issue by Alegoper** [P3pp3rF1y/SophisticatedBackpacks#1075]
When i have experience stored in a tank on my netherite backpack on the curios slot and I die and go to retrieve my items with the gravestone/corpse mod (it happened with both) it crashes every time i open my inventory. Also, I can't open the curios menu if I have experience on the tank

**To Reproduce**
1. Open backpack
2. Have experience on a backpack tank
3. Die and pick up things with gravestone/corpse mod

**Expected behavior**
Not crash the game

Using version 1.19.2

**Comment by P3pp3rF1y** [comment]
I need the crashlog.

Very much doubt it's just xp in tank because that's way too common thing. Likely some other mod is causing it especially when it happens when picking up from grave because there isn't supposed to be any difference in this case vs just picking up backpack from a chest or ground or similar.

**Comment by P3pp3rF1y** [comment]
closing given no response
