### ISSUE TITLE
right click a backpack with a item in creative delete the item

### ISSUE THREAD

**Issue by 1Flick** [P3pp3rF1y/SophisticatedBackpacks#1079]
**Describe the bug**
only using SB

**To Reproduce**
1. Open inventory
2. Right click items in the backpack in creative
3. The item disapears

**Expected behavior**
the item just desapears

**Versions**
sophisticatedbackpacks-1.19.2-3.20.2.1035.jar
sophisticatedcore-1.19.2-0.6.4.605.jar

**Comment by P3pp3rF1y** [comment]
yes that is a "feature" of creative. I guess what I could do here is just prevent the stashing in creative altogether if that's even possible. I will take a look at that.

**Comment by P3pp3rF1y** [comment]
And nope I can't prevent this from happening in creative. Potentially could stop the display of the stash icons but the stashing would still "work" as in would delete the items in creative because in my code I can't tell if the player is in creative or survival. Would require very intrusive changes on higher level which I just don't want to spend time implementing / maintatining. So closing this
