### ISSUE TITLE
Tank breaks if placed on a Mekanism pipe

### ISSUE THREAD

**Issue by Potatuhm** [P3pp3rF1y/SophisticatedBackpacks#1082]
**Describe the bug**
Experience pump / Tank stops working at all if placed on a Mekanism Pipe. 
No Crash.
Mekanism, we have other mods but they don't feel related to this issue.

**To Reproduce**
1. Place a backpack with the tank and exp pump upgrade on mekanism pipe
2. Click on the pump upgrade
3. Try to take / store exp

**Expected behavior**
That the tank / pump upgrade should still work

**Screenshots**
N/A

**Versions**
1.20.1-3.20.5.1044 
forge version 47.2.0

**Comment by P3pp3rF1y** [comment]
I am unable to recreate this bug and really doubt that experience pump would break that way because it has nothing to do with pipes. Tank does but that would require the pipe to e.g. take fluid out. In case you would be able to give me more details I can try with those otherwise I am just going to close.

**Comment by P3pp3rF1y** [comment]
closing given no additional info was provided here
