### ISSUE TITLE
Backpack vanish on death

### ISSUE THREAD

**Issue by Aho-Senpai** [P3pp3rF1y/SophisticatedBackpacks#109]
**Describe the bug**
Backpack vanished after death. could be an issue with corail tombstone mod? currently playing on ATM6S modpack

**To Reproduce**
Backpack in inventory
death in the end
backpack vanish upon collecting the grave

**Expected behavior**
backpack still being present

**Versions**
1.16.4-2.2.7.222

**Comment by Aho-Senpai** [comment]
I'm sorry, my mistake. it went to the curio slot by default. first time i see an item that does that.

**Comment by P3pp3rF1y** [comment]
Just fyi after discussing this on discord and the example of powah battery that doesn't go in there I took a closer look at this and I can see why that is not the case for battery - there are basically two things about curio compatibility - one is basically just marking the item with name of slot that it should go in (by default only preferred) and the other is implementation of any special functionality apart from just being able to run in the slot. Tombstone for some to me unknown reason relies on that second part and the difference between battery and backpack here is that battery just runs from the slot so it doesn't require any special implementation where backpack needs to be rendered and thus needs this special implementation and that's why tombstone treats it as curio item where it doesn't treat battery as one.
My thought on that is this likely not intended and tombstone mod in fact wants all of the curio items to be autoequipped and should rely on the simple tag for that.
