### ISSUE TITLE
Crash with Candlelight

### ISSUE THREAD

**Issue by hu7x** [P3pp3rF1y/SophisticatedBackpacks#1095]
**Describe the bug**
Crash Log:https://pastebin.com/WfYUZ113

**To Reproduce**
1. Open backpack
2. Put feeding upgrade in backpack
3. Put Candlelight's Food
4. While Auto Feed
5. Game Crash

**Expected behavior**
Candlelight's Food cannot be eaten in one go,this could be the cause of the crash

**Screenshots**
None

**Versions**
 Sophisticatedbackpacks-1.20.1-3.20.5.1044
 Sophisticatedcore-1.20.1-0.6.22.611

**Comment by P3pp3rF1y** [comment]
This happens because candlelight is looking for the stack in player's inventory and when it can't find it there it tries to access non existent slot and crashes on that. They appear to have this fixed in farm and charm compat branch that appears like something that needs to be released. Anyway this would happen if any other mod tried to do similar thing - trigger eat code when the item isn't in player's inventory - and should be fixed on candlelight's side.
