### ISSUE TITLE
1.18.2 Exp pump pumps out more Exp than put in

### ISSUE THREAD

**Issue by BoonyisMe** [P3pp3rF1y/SophisticatedBackpacks#1099]
I'm unsure if this is intended but i often get more than i put in, which i'm not complaining, but it seems a bit unfair. I always thought the output was heftier than the input.

**To Reproduce**
1. Open backpack
2. Pump in experience (For example i pumped in 8)
3. Pump out experience (I got 12 in return)

**Expected behavior**
Getting 8 back

**Screenshots**

**Versions**
1.18.2

**Comment by P3pp3rF1y** [comment]
This is likely because in 1.18 I still rely on a variable that vanilla has for the total player experience but doesn't update it in all cases. For example when you use anvil I am pretty sure this isn't updated and because of that experience upgrade will get more xp from that variable on player than they are supposed to have.
I have this fixed in 1.20.1 and honestly I don't feel like this is that critical to require fix in 1.18.2 because you can't really repeat getting that extra xp, you would have to spend xp to get back the xp that you spent. Also 1.18 has been around for a really long while and this is probably like 2nd time I am hearing about the issue despite many people using the upgrade. So I am going to close in favor of spending more time on newer versions.
