### ISSUE TITLE
A network channel error message appeared while connecting to the server

### ISSUE THREAD

**Issue by openthedoge** [P3pp3rF1y/SophisticatedBackpacks#1113]
After removing the module, it can be accessed normally. Perhaps it is a problem caused by the profound-core module. I have placed the logs and screenshots here
Client[latest.log](https://github.com/user-attachments/files/16598577/latest.log)
server[serverlog.txt](https://github.com/user-attachments/files/16598578/serverlog.txt)
![2024年8月13日](https://github.com/user-attachments/assets/1be41417-6e11-4c1a-b0f2-74443554e268)

**Comment by openthedoge** [comment]
NEOforge21.1.8

**Comment by P3pp3rF1y** [comment]
This happens when you don't have sophisticatedcore loaded on server, is server log showing that it loaded properly / showing an error that it hasn't loaded?

**Comment by openthedoge** [comment]
> This happens when you don't have sophisticatedcore loaded on server, is server log showing that it loaded properly / showing an error that it hasn't loaded?

I did not load the core separately for this test, I only tried uninstalling other mods for comparison. I always put the backpack and core in the same comparison group   T T

**Comment by P3pp3rF1y** [comment]
The question still stands - does the server log show core loading properly or does it show any error? Can you share the server log?

**Comment by openthedoge** [comment]
> The question still stands - does the server log show core loading properly or does it show any error? Can you share the server log?

I'm sorry, maybe I'm not quite sure how to export the normal operation log of the server because it didn't generate any errors that caused the server to shut down. It just prevented me from entering the server and added an extra message that I had already sent above. Please forgive my foolishness, I can't find the path to this normal operation log. I can try again later

**Comment by openthedoge** [comment]
I performed the following actions: I started the server, then the client logged into the server twice, and then I shut down the server.
The following log has been generated. I'm not sure if this is the log you want
[archive-2024-08-15T130227+0800.tar.gz](https://github.com/user-attachments/files/16621667/archive-2024-08-15T130227%2B0800.tar.gz)

**Comment by P3pp3rF1y** [comment]
To be honest no idea why it's not working for you, I know for sure that multiple people play on servers with my 1.21 mods already and just to be sure tried with latest 1.21.1 server / client and everything connects correctly. So it's very likely one of the other mods you have there. Can you try with just sophisticated?

**Comment by ndv01** [comment]
I found that if put with JEI Mod cause this issue, i hope it can help you fix it...

Edit: BTW i tried with Several versions of JEI and all of them in 1.21.1 appears to have this issue.

**Comment by P3pp3rF1y** [comment]
@ndv01 I was surprised to hear something like that because JEI is used in almost every pack. Tried adding it and I am again unable to recreate. 

So I still need to understand how I can recreate this, but it really feels like a mod or server issue that's causing core not to load on server or error out for some reason for you.

**Comment by ndv01** [comment]
i have my server with mods that i know that works fine, when i install the JEI mod into my client side and try to join my full functional server, then the error appears.

i managed to get it working using REI mod instead of JEI.

**Comment by P3pp3rF1y** [comment]
Ah right, JEI only running on client. That is an issue because I only check if JEI is available on client and register the compat based on that. I will need to check into if and how it is possible to figure out if JEI is available on server, but honestly this complicates the integration quite a bit because it's not just network but other functionality as well that would have to be made conditional or simpler way would be just to drop the JEI integration altogether if server doesn't have JEI. Easy solution for you is to add JEI server side as that anyway provides you with more functionality.

**Comment by P3pp3rF1y** [comment]
Apparently I can just mark the payloads optional so I am going to fix it like that for the next release.

**Comment by P3pp3rF1y** [comment]
Released the fix on CF
