### ISSUE TITLE
Crash at world laoding

### ISSUE THREAD

**Issue by agentwolf88** [P3pp3rF1y/SophisticatedBackpacks#112]
**Describe the bug**
Crash at world loading

**Versions**
sophisticatedbackpacks-1.16.4-2.2.8.234.jar
Forge: net.minecraftforge:36.1.0

https://paste.ee/p/YSFzC

**Comment by P3pp3rF1y** [comment]
Could you just confirm for me one thing? I am guessing you have switched from one world to another while still running the modpack right?

**Comment by agentwolf88** [comment]
I have saved my world and loaded the world a second time.

**Comment by P3pp3rF1y** [comment]
yup, so I am pretty sure what happened is there was a sound playing from one of the backpacks and info on that stayed in the cache and then when the world was loaded the second time it actually seems to be able to run world tick before there is connection to the world and tries to tell server the sound is no longer playing on client but crashes on missing connection. I will get this fixed so that the cache is cleared when player leaves world / logs out from server

**Comment by agentwolf88** [comment]
Thx, keep up the good work!

**Comment by P3pp3rF1y** [comment]
this is now fixed in the latest release on CF
