### ISSUE TITLE
Requesting support for Etched music discs

### ISSUE THREAD

**Issue by BreakerOfMaps** [P3pp3rF1y/SophisticatedBackpacks#1148]
The Jukebox upgrade does not allow any music disc originating from the Etched mod to be fitted into the disc slot. However, any normal disc from vanilla game works perfectly fine in the slot.

1. Open backpack
2. Click on Jukebox tab
3. Attempt to put a finished Etched music disc into the Jukebox slot
4. Nothing happens, as the disc is not recognized as being a music disc

**Expected behavior**
Disc should fit into the Jukebox slot as expected

**Versions**
1.20.1 - 47.3.0
(ps sorry if its a bad report, i am a bit new around here)

**Comment by P3pp3rF1y** [comment]
That would require explicit compat in versions previous to 1.21. In 1.21 there are now standard components that allow support for custom music on modded discs so if etched will continue in 1.21 it should implement these and will be automatically supported. Given this I decided to close the requests for etched compat because it would be for old versions only
