### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by danymo1221** [P3pp3rF1y/SophisticatedBackpacks#117]
**Describe the bug**
Info on what other mods you're using that may cause a conflict here if applicable.
When doing the steps below your client and the server will both crash

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
It’s when you put something that isn’t an upgrade into an upgrade slot

It crashes your game and the server apparently
**Expected behavior**
Server and client instantly crashes

**Screenshots**
The server keeps crashin

**Versions**
Mod version that you're using. Version of forge may also be helpful in some cases
Sophisticatedbackpacks-1.6.4-2.2.8.232.jar

Error Log
[crash-2021-04-07_00.15.23-server.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/6280159/crash-2021-04-07_00.15.23-server.txt)

**Comment by P3pp3rF1y** [comment]
This is fixed in version 234 - second to last as of now. In that version it again properly checks for only upgrades going into the slot in all scenarios. However if you already have a backpack with another item in upgrade slot that won't stop this crash. you will need to ditch the backpack / load from backup or edit the nbt of the backpack to get the item out of there.
