### ISSUE TITLE
Game Crashes on startup when using latest Sophisticated mods on Neoforge

### ISSUE THREAD

**Issue by ExiledMiner04** [P3pp3rF1y/SophisticatedBackpacks#1170]
**Describe the bug**
Try to run the game on 1.21.1 neoforge 21.1.62+ and it crashes on startup.

**To Reproduce**
Install latest Sophisticated backpacks, core, and storage and try to run the game.

**Expected behavior**
Should run normally and can play a world.
**Screenshots**

**Versions**
sophisticatedbackpacks-1.21-3.20.16.1111
sophisticatedcore-1.21-0.6.42.712
sophisticatedstorage-1.21-0.10.44.906
Neoforge 1.21.1 21.1.62 up to 21.1.65

[crash-2024-10-03_18.17.50-client.txt](https://github.com/user-attachments/files/17250928/crash-2024-10-03_18.17.50-client.txt)

**Comment by P3pp3rF1y** [comment]
This is definitely not caused by sophisticated because it crashes when some mod tries to apply its mixins to a class. Sophisticated doesn't use any mixins at all and the only reason it is mentioned in the crash log is because that other mod's mixin error happens when sophisticated tries to register its entity renderers. 

Likely issue here is that the other mod is made for a different version of mc / neoforge and you will need to figure out what that other mod is and remove / update to a version that works well with your version of neoforge / mc (depending on what code that mod is trying to change).

**Comment by taldofelp** [comment]
did you ever figured out what was causing it?
