### ISSUE TITLE
When using stack upgrades, the total stack size increments along with the stack size.

### ISSUE THREAD

**Issue by haster789** [P3pp3rF1y/SophisticatedBackpacks#1197]
Netherite backpack, 3 Stack tier level 4 upgrades, when hovering over the stack in your backpack, both numbers increment when you are   adding things to the backpack. 

Don't know if you can upload pictures, but I'm gonna try.

![2024-11-07_08 40 37](https://github.com/user-attachments/assets/874f6785-fb6e-4a0a-b9e7-2a015d8a1572)
![2024-11-07_08 42 15](https://github.com/user-attachments/assets/1127735b-db94-4e79-bef2-9ede7622584c)

**Comment by haster789** [comment]
After looking over what I missed, wanted to include: 
Allthemods10 modpack
version 1.21.1
Neoforge 21.1.73

**Comment by P3pp3rF1y** [comment]
Have you got any other mod added that modifies maximum stack size? Because with those stack upgrades the limit per slot should be 16,384 and I am unable to recreate any issue with just sophisticated.

**Comment by haster789** [comment]
No other stack modifications, I will grab my save game and reinstall ATM10

**Comment by P3pp3rF1y** [comment]
I see what's very very likely happening in your case - some mod is modifying max stack size to be equal to the actual stack size there and because total slot limit is based on the stack's max stack size it keeps staying at 256x current max stack size = 256x current count. Now the only question is what mod is doing that, I would suspect either the mod that's inserting into this backpack you're using there or some mod directly modifying any ItemStack. Have you got just pure ATM10 modpack or you have added anything on top of that? And is this in single player?

**Comment by haster789** [comment]
Single Player, yes, actually made a backup of my mods folder, digging into it right now, I know i added a few things, just making sure they don't modify the stack size.

**Comment by haster789** [comment]
Not able to recreate after reinstall, so must of been of the additional mods i added, will be adding those later today, I could update you if I find which mod was causing the issue.

**Comment by P3pp3rF1y** [comment]
> Not able to recreate after reinstall, so must of been of the additional mods i added, will be adding those later today, I could update you if I find which mod was causing the issue.

Did you find what mod caused it? I could potentially double check if I am doing something non standard that contributes to this issue if so. Otherwise I am going to close.

**Comment by P3pp3rF1y** [comment]
closing given no additional info
