### ISSUE TITLE
Etched disks not compatible with music player upgrade

### ISSUE THREAD

**Issue by collatzcoder** [P3pp3rF1y/SophisticatedBackpacks#1199]
**Describe the bug**
No music discs from etched, a custom music disc mod, work in the music player upgrade

**To Reproduce**
1. Open backpack
2. Click on music player tab
3. Attempt to put in the disc
4. Does not even go in

**Expected behavior**
I expected it to go in and be able to play.

**Screenshots**

https://github.com/user-attachments/assets/3d8b5543-9681-4681-8516-d053b15691ff

**Versions**
1.20.1-3.20.11.1115

**Comment by P3pp3rF1y** [comment]
Not a bug as Etched uses their own custom logic and there was neve compatibility for this. Anyway in 1.21 custom music discs are supported by vanilla out of the box so if etched ever happens to port it should just use that system and it will be automatically compatible with SB. I am not going to add compat in previous versions.

**Comment by the-one-with-raspberry** [comment]
Does it? In the official [List of components](https://minecraft.wiki/w/Data_component_format#List_of_components) there's nothing referring to jukebox songs other than `jukebox_playable` which expects a jukebox song ID. Probably just didn't look far enough though.

**Comment by the-one-with-raspberry** [comment]
This is not objectified. First off, for custom Music Disc designs you would need a whole another item for THAT specific Music Disc pattern, as the item IDs are `minecraft:music_disc_<name>`. Second, the datapack logic is quite complicated for the user that just wants to add their own custom music disc without diving through the game's code.

**Comment by P3pp3rF1y** [comment]
@the-one-with-raspberry the `JUKEBOX_PLAYABLE` component allows definition of any registered song as something that is played when that specific item plays. And I am saying item intentionally here because in theory you can just plop this on a stick and it will play in jukebox (in fact saw a video of someone putting music on stuff like pufferfish / diamond / similar. So what would be required here is register a new music in jukebox songs registry and then just put this component on whatever custom disc item that points to that newly registered song.
That said Etched ported to 1.21 and doesn't seem to use this system for some reason so I will be taking a look at that at some point in the future.

**Comment by the-one-with-raspberry** [comment]
Okay, but defining a Music Disc is still pretty complicated for the average user.

**Comment by collatzcoder** [comment]
Seeing as I get these emails now, if etched didnt use the standard jukebox
system to make custom music in 1.20, then does it use the new system in
1.21?
