### ISSUE TITLE
Mod fails to load with Eclipse OpenJ9

### ISSUE THREAD

**Issue by renandadalte** [P3pp3rF1y/SophisticatedBackpacks#120]
I was trying to load Minecraft with AdoptJDK OpenJ9 and my launcher crashed, log file:

[crash-2021-04-20_17.12.41-fml.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/6346439/crash-2021-04-20_17.12.41-fml.txt)

**Comment by P3pp3rF1y** [comment]
This is because forge has issues with OpenJ9 and apparently that JVM isn't supported so what's described in this reddit may work for you but I would rather recommended using different OpenJDK vm
 https://www.reddit.com/r/feedthebeast/comments/dxncil/i_cant_play_on_forge_using_openj9/

and there's apparently supposed to be crash even before what you caught that would tell you 
the vm is unsupported https://github.com/cpw/modlauncher/commit/1f9473a28ad910ef42539f7f789f63afa4cdbf8d
