### ISSUE TITLE
Suspected due to Sophisticated Backpacks, player data on the server cannot be saved properly

### ISSUE THREAD

**Issue by Lumine139637659** [P3pp3rF1y/SophisticatedBackpacks#1210]
**Describe the bug**
It should be that after using 'Stack Upgrade Tier', the server console told me that the number of items exceeded the upper limit abnormally, making it impossible to save player data, resulting in the player being immediately kicked out after entering the world（machine translation）
应该是使用“Stack Upgrade Tier”以后，服务器控制台告诉我物品数量异常超过上限，无法保存玩家数据，导致玩家进入世界后马上被踢出
[
[crash,debug,latest.zip](https://github.com/user-attachments/files/17783916/crash.debug.latest.zip)
](url)
**To Reproduce**
Unable to reproduce errors stably

**Expected behavior**
Can save player data normally

**Screenshots**
![f007962d705d295f0bad2caacd5d0d8a](https://github.com/user-attachments/assets/6c44ce4d-6373-4db5-ab83-1a93dc6a1517)

**Versions**
1.21-3.20.18.1117，neoforge21.1.77

**Comment by P3pp3rF1y** [comment]
That issue was fixed already, just update to latest core and backpack/storage and it's done.

**Comment by P3pp3rF1y** [comment]
also this has nothing to do with saving SB data it only happened during feeding the player where apparently in this case SoL Onion for some reason saves the stack that player has in their hand and because it was larger than 99 it couldn't. anyway in newer versions the player will have a stack of max 1 in their hand when the feeding upgrade feeds them
