### ISSUE TITLE
Music disc module sound stacking

### ISSUE THREAD

**Issue by Bitlod** [P3pp3rF1y/SophisticatedBackpacks#1234]
**Describe the bug**
When mob spawn, he can wear backpack with music disc in it and play the sound. This is funny feature, but when the night comes, many mobs using jukebox at the same time and it sound terryfying. Also if mob spawned in the caves, i can still hear him, but can't kill for stopping that music.
Pls add in config turning off music sound or cut music hearness radius(like 5 blocks near the mob with reducing sound if the player too far from it or smf like that.
**Expected behavior**
Turning of mob music disc sound + player can't hear music from it if mob is too far from him

**Versions**
Forge 1.20.1

**Comment by P3pp3rF1y** [comment]
You would only hear a lot of music overlapping if either you have the chance of spawning with backpack set way too high or potentially it could sometimes happen if mods are adding discs that have music in stereo which in that case isn't localized and plays at the same volume however far you are from jukebox (even vanilla one). Which is the explanation for your second point. The mod(s) that's adding the disc should really fix the music to be mono and thus could be localized by minecraft, but you can also use `discBlockList` in config to list discs that are broken this way so that they wouldn't appear in backpacks. Let me know if you have any other issue here otherwise I am going to close.

**Comment by Bitlod** [comment]
Got it
Thx for the answer, ill try to do smf about it my own
P.S: U've made cool balanced backpacks, well done!

**Comment by Bitlod** [comment]
Oh i sorry, how and where to create discBlockList file?

**Comment by P3pp3rF1y** [comment]
Search for that in sophisticatedbacpacks-server.toml config file

**Comment by Bitlod** [comment]
Ok thanks again!
