### ISSUE TITLE
in mohist forge server，may when a mob spawn with backpack，the server will stop

### ISSUE THREAD

**Issue by huntersxy** [P3pp3rF1y/SophisticatedBackpacks#1241]
**Describe the bug**
from log，may when a mob spawn with backpack,the server will stop.
I don't know which aspect of the problem it is, mod? Server core?
**To Reproduce**
1. just afk

**Expected behavior**

**Screenshots**
server problem，only log

**Versions**
sophisticatedbackpacks@3.20.17.1150
i try sophisticatedbackpacks@3.20.17.1126，still have problem
[1.log](https://github.com/user-attachments/files/18209878/1.log)

**Comment by P3pp3rF1y** [comment]
I don't see the actual exception in that log so I will need the full stack trace or even better if you have actual crash log for this.

**Comment by huntersxy** [comment]
[crash-2024-12-20_17.47.11-server.txt](https://github.com/user-attachments/files/18211923/crash-2024-12-20_17.47.11-server.txt)
sorry,i upload now@P3pp3rF1y

**Comment by P3pp3rF1y** [comment]
PasterDream mod is trying to check value of some attribute that the mob doesn't have and so it crashes. I don't mess with removing attributes so it's missing because either they haven't added it or they don't properly account for states in which the attribute may not exist. Either way this one would be for them to fix, easiest way would be to just plain check if the mob actually has the attribute before checking its value.

**Comment by huntersxy** [comment]
thank you
