### ISSUE TITLE
Inventory Sorting mod deletes items.

### ISSUE THREAD

**Issue by judicius** [P3pp3rF1y/SophisticatedBackpacks#140]
**Describe the bug**
When utilizing a stack upgrade, in this case Tier 4, and having item stacks above 64 in the backpack. Utilizing the hot key from the mod inventory sorter, the stacks are spread through out the backpack as stacks of 64. If there are other items in the backpack they disappear ( assume voided).

**To Reproduce**
1. Open backpack
2. Fill all slots with a stack of 64 of the same item, and then use backpack sort button to condense.
3. Add a stack of 64 of a second item
4. Use inventory control sorting, first item will spread out in stacks of 64 and 'push' the second item into the void.

**Expected behavior**
inventory control sorting to work the same as backpack sorting, or to be disabled completely so as to not accidentally delete items

**Versions**
MC 1.16.5
Forge 36.1.16
SoBags 2.4.0.259

**Comment by P3pp3rF1y** [comment]
I have added the backpack inventory slot to Inventory Sorter's blacklist using its compatibility stuff, but I am afraid that's not going to help as the mod has bug in there which basically ignores what it received and overrides it with what it has in config I believe or even with just empty blacklist. That was the case when I was testing other slots with it and debugged it to the bug in there and since that time there wasn't a single change to the mod. So you're better off using another mod for inventory sorting like inventory tweaks.

**Comment by judicius** [comment]
You added it through the commands or you added the containerClass directly into the config?

**Comment by P3pp3rF1y** [comment]
I am adding it through intermod compatibility inventorysorter has. I can't use commands or config that's for the player to use.

**Comment by P3pp3rF1y** [comment]
the compat added in the latest release on curseforge
