### ISSUE TITLE
Unable to start server when using mod

### ISSUE THREAD

**Issue by polios3** [P3pp3rF1y/SophisticatedBackpacks#173]
**Describe the bug**
i'm unable to start server when this mod is installed. i attach log file.
[2021-07-05-1.log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/6766107/2021-07-05-1.log)

i'm using MohistMC. to use Forge mods and Bukkit plugins. i can add later full plugins list.

the only error that occurs is unrelated to this mod. but this bug disappears after removing your mod. so i don't know. on single player world all work fine with all datapacks and mods.

**To Reproduce**
1. install mod on MohistMC
2. maybe work?? maybe don't? i need to see on clean MohistMC

**Versions**
sophisticatedbackpacks-1.16.4-2.5.0.271
client -forge 36.1.32

**Comment by P3pp3rF1y** [comment]
your issue seems to be this `[21:22:58] [main/WARN] [net.minecraft.server.Main/]: Failed to load datapacks, cant proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode` not sure what kind of datapacks you have there, but please when you log an issue for a mod be at least a bit more sure about mod having an issue and provide crash log or error log that shows the issue. 
I am not support for MohistMC, but I can tell you that this mod is run on many servers without any issue. 

If you find that there really is an issue with sbp feel free to open an issue with more details included.
