### ISSUE TITLE
Server crash on resource manager reload

### ISSUE THREAD

**Issue by PapiOphidian** [P3pp3rF1y/SophisticatedBackpacks#178]
This crash seems to be related to #174 and #173
Unlike 174, I do not use MohistMC and instead use Forge 1.16.5-31.6.32

Removing this mod does not cause any issues.
Stack: https://pastebin.com/MS4Ke74y

Previously, I thought it was related to FastWorkbenchNoReplacement, but removing that does not fix it.

Mod version 
1.16.4-2.5.0.271

**Comment by PapiOphidian** [comment]
It seems as though this is an issue with generating the config initially. We got our hands on a fully loaded config and dropped it into the server and it loaded fine.

**Comment by PapiOphidian** [comment]
misclick

**Comment by P3pp3rF1y** [comment]
yeah, this is the exact same issue as #174. Not sure why it doesn't crash for me even with missing config, but it appears that something makes recipes load in concurrent fashion and that causes the CMI. I have a fix in dev that uses thread safe collection there so this will be fixed in the next release.

**Comment by P3pp3rF1y** [comment]
fixed in the latest version
