### ISSUE TITLE
Toolswapper Keybind Not Working

### ISSUE THREAD

**Issue by iAmAutolocker** [P3pp3rF1y/SophisticatedBackpacks#190]
**Describe the bug**
When my crosshair is aimed at a block, and I use the toolswapper keybind (which I set to V, with no conflicts), the applicable tool doesn't go to my hand.

**To Reproduce**
1. Put a complete set of tools within the backpack.
2. Use the toolswapper keybind.

**Expected behavior**
Whatever I am currently holding, or my empty hand, gets replaced with a suitable tool.

**Screenshots**
![2021-07-26_14 47 32](https://user-images.githubusercontent.com/84983504/126945603-32caa684-8c06-461d-8a9a-0abaf87b7ef7.png)
My Keybinds

![2021-07-26_14 47 38](https://user-images.githubusercontent.com/84983504/126945617-64ee6c63-b45f-4374-8542-f2726f65dcab.png)
The insides of the backpack

![2021-07-26_14 47 46](https://user-images.githubusercontent.com/84983504/126945625-299ef209-c40b-4c08-8a1a-1da46874e755.png)
Aiming my crosshair at a dirt block and pressing the keybind

![2021-07-26_14 47 52](https://user-images.githubusercontent.com/84983504/126945648-61a8df82-f1dd-4ac6-b22d-f669e2c9d0d4.png)
Aiming my crosshair at ore and pressing the keybind

**Versions**
sophisticatedbackpacks-1.16.4-3.0.0.289
Forge 36.1.65

**Other Notes*
Toolswap works perfectly fine when I attempt to destroy a block. Grass blocks and Oak log are the only blocks I've aimed at where the keybind worked correctly.

Here's my modlist, but I doubt it matters since its what I use for testing. Pretty much only library mods.
'AppleSkin' (appleskin:mc1.16.4-2.0.0), 
'Architectury' (architectury:1.17.22), 
'BdLib' (bdlib:1.17.1.11), 
'Click Machine' (clickmachine:4.4.0), 
'Collective' (collective:2.27), 
'Controlling' (controlling:7.0.0.23), 
'CreRaces' (creraces:b1.1.3), 
'Curios API' (curios:1.16.5-4.0.5.2), 
'Cyclops Core' (cyclopscore:1.11.7), 
'Forge' (forge:36.1.65), 
'FTB GUI Library' (ftbguilibrary:1605.2.1.41), 
'FTB Library' (ftblibrary:1605.3.1-build.26), 
'JEI Integration' (jeiintegration:7.0.1.15), 
'Just Enough Items' (jei:7.7.0.106), 
'Just Enough Resources' (jeresources:0.12.1.121), 
'Lollipop' (lollipop:3.2.9), 
'McJtyLib' (mcjtylib:1.16-5.0.19), 
'Minecraft' (minecraft:1.16.5), 
'MmmMmmMmmMmm' (dummmmmmy:1.2.0), 
'Mod List Paster' (modlistpaste:1.2.0), 
'Patchouli' (patchouli:1.16.4-51), 
'Placebo' (placebo:4.5.0), 
'Potato Cannon' (potatocannon:1.0.2), 
'Powah' (powah:2.3.16), 
'Ring of Repair' (ring_of_repair:1.2.15), 
'Shrink' (shrink:1.1.5), 
'Shutup Experimental Settings!' (shutupexperimentalsettings:1.0.3), 
'Sophisticated Backpacks' (sophisticatedbackpacks:1.16.4-3.0.0.289), 
'Superflat World No Slimes' (superflatworldnoslimes:1.4), 
'Technobauble' (technobauble:0.2.0.5), 
'The One Probe' (theoneprobe:1.16-3.1.4), 
'TrashSlot' (trashslot:12.2.1)

**Comment by P3pp3rF1y** [comment]
well toolswapper has two separate things happening
- one is where you can left click something and toolswapper can react to that - digging, cutting down log, attacking an entity. In that case all that's required is you having a weapon or tool in hand that you are left clicking with and the rest of tools in backpack and it will automatically switch these (just note that at the moment it doesn't do that for tinkers or tetra tools because they don't have their tools marked with types as vanilla does. I am looking into a good fix to take care of that
- second is where the tool you need is actually right clicked. Because it would be very annoying if something swapped into your hand every time you would right click this is where the keybind is used to swap in your hand the tool that's applicable to the given block (mostly wrenches, bucket and shears for entities and some other stuff that can apply to both blocks and entities)

I guess I could include the tools from the first set in the second one as well, it just makes that set larger mean you need to click the keybind multiple times to get what you want and you would be getting for example pickaxe for all kinds of pipes.

I will leave this open and think about if I want to make an additional change and if and how I can better communicate how the upgrade works

**Comment by iAmAutolocker** [comment]
Oh, I see. Leaving the keybind to work with wrenches does make perfect sense. Maybe just a config option then (like a whitelist)? Or adding another 'type' to the tool swapper (weapons, tools, and wrenches)

**Comment by P3pp3rF1y** [comment]
In the latest release tool swapper tooltip has more detailed information on how it swaps tools with left click and right clickable ones with the keybind
