### ISSUE TITLE
ToolSwapper not working appropriately with Tetra tools

### ISSUE THREAD

**Issue by QuantumBreed** [P3pp3rF1y/SophisticatedBackpacks#199]
**Describe the bug**
I am trying to use the advanced backpack swapper with tools modified by the Tetra mod in Enigmatica 6 modpack. I am able to force it to change when holding to a vanilla tool but it does not grasp which tool to use at the right time, (I.E swapping to hoe with sickle head to chop tree or axe to dig dirt. placing the specific item in each slot to define it as the appropriate tool does not switch to that tool no matter the settings.

**To Reproduce**
1. Open backpack
2. Click on on settings for Advanced Tool Swapper
3. Place Tetra converted tools into watch slot to define them as that tool.
4. Have weapon and tool clicked to swap.
5. Have allowed
6. Have match Tags/Mod/Item on (all three change nothing)
7. Have Have match NBT on match
8. have wooden tool in hand
9. click on different blocks with wooden varients and Tetra tools in backpack
10. have only wooden variants swap out of bag
11. Use keybind to try to remedy
12. keybind says there is no tool that works on this with dirt and stone while using it on wood swaps it with Tetra axe, Wooden axe and Tetra shovel.

**Expected behavior**
Placing specific items into the slots of the Advanced Tool Swapper makes that tool appear when i click on a block associated with it. Clicking on dirt/grass/mycelium will switch to the shovel or other item i have set in the shovel slot.

**Screenshots**
![Screenshot 2021-08-03 101049](https://user-images.githubusercontent.com/30003932/128030342-80d77dce-bbcb-4fc5-9bc4-a9e56168bee0.png)

**Versions**
sophisticatedbackpacks-1.16.4-2.5.0.271.jar that is currently included in Enigmatica 6 0.5.6.
Updated mod to sophisticatedbackpacks-1.16.5-3.0.3.297.jar and same steps applied.

**Comment by Drakoflame** [comment]
I'd reason it has something to do with the way Tetra tools are registered. I've had weird interactions with the dirt-to-path feature of Quark when using a Tetra Pickaxe sometimes. It might just be that the Tool Swap feature isn't smart enough to see the difference, or it's just the way Mickelus has the tools coded (so that they can be used as a pick/axe/shovel/hoe. They've had questionable interactions with Minecolonies as well, and Mickelus is aware of them

**Comment by P3pp3rF1y** [comment]
the reason here is that in vanilla/forge we have tooltypes assigned to tools (pickaxe/axe/...) but Tetra doesn't use these and has a different system. I will need to look into how to treat these, will likely require some level of compatibility for Tetra but I should be able to fix that and is something I would like to take care of in the next release.

**Comment by P3pp3rF1y** [comment]
The latest release on curseforge has a tuned logic that works with Tetra tools
