### ISSUE TITLE
Auto-feeding upgrade does not provide food values for Diet mod

### ISSUE THREAD

**Issue by Not-February** [P3pp3rF1y/SophisticatedBackpacks#211]
**Describe the bug**
When food is consumed via the auto feeding upgrade, you do not gain associated diet values from eating the food if you have Diet installed.

**To Reproduce**
1. Have both Diet and Sophisticated Backpacks installed
2. Select a food with Diet values for the auto feeding upgrade
3. Check your diet values
4. Have the auto feeding upgrade trigger
5. Check diet values again, it probably didn't change at all

**Expected behavior**
I would expect eating food to give the diet values associated, even if eaten automatically through the backpack.

**Versions**
``Forge 36.2.0``
``Sophisticated Backpacks 3.0.3.297``
``Diet 0.38``

**Comment by P3pp3rF1y** [comment]
Interesting, based on what I am seeing I am triggering the right event (and actually based on interaction with spice of life CE I know that is working properly) and I can see Diet using that exact same event to trigger its stuff. 
Will probably need to debug why this is not happening, not sure if issue is on my or their side.

**Comment by P3pp3rF1y** [comment]
And this is the same as the other ticket - it's working properly for me. a few vegetable soups were eaten and I have got vegetable bar going up in the diet screen and once I switched to chicken in my backpack protein started going up. So this is working properly for me as well.
the only thing I can guess is that you have some mod in your modpack which affects item use finish event and causes these issues for you.

let me know if you have any additional info I could use to recreate, but otherwise I will close after some time

**Comment by Not-February** [comment]
Just to double check - this isn't the kind of thing that having a custom diet category would affect in any way, is it?

**Comment by Not-February** [comment]
Okay, I've been doing a second pass of testing and haven't been able to reproduce either of the issues again. The only thing I can think of is that I somehow didn't notice the values update or perhaps server latency contributed to it appearing as though the soup stack wasn't going down immediately.

I apologize for taking up your time.
