### ISSUE TITLE
Accidentally put my backpack inside itself--and now I can't access it anymore

### ISSUE THREAD

**Issue by ThisWhomps** [P3pp3rF1y/SophisticatedBackpacks#24]
Like the title says. I was idly moving some things between inventory and the backpack, and somehow I was able to stow the backpack within itself, along with all of my important items (naturally), and now I can no longer open it or find it. I'm playing on 1.16.4 and I've not previously been able to stow the backpack within itself. I've only applied a gold/magnet filter to it so I haven't done anything new. 

Is it just gone or can I get it back?

**Comment by P3pp3rF1y** [comment]
The only way I can think of this happened is with the oldest version - because you don't mention inception upgrade and it was only possible to insert backpacks into backpack without that upgrade in the oldest version. Then in combination with sorting mod it was possible to have backpack moved to a slot that wasn't locked and then you would be able to put it into itself. At that point you had new copy of your backpack in inventory, but gui was open for backpack that no longer existed (as the sorting mods delete the previous stacks after moving stack into new position). So then it didn't have where to save.
It's a lot of guessing, but if this what happened to you the backpack would have just disappeared and there's no getting it back. 

I would recommend playing with newest versions of the mod where nothing of this is possible.
