### ISSUE TITLE
Crash when backpack is shift clicked into Curios slots

### ISSUE THREAD

**Issue by Random-Scientist** [P3pp3rF1y/SophisticatedBackpacks#258]
pretty self explanatory

To Reproduce:
Install curios and this mod. 
open curios inventory with the button
shift click a backpack into that from your main inventory

Expected behavior:
backpack get shifted to Back curio slot, game doesn't crash

Mod version:
3.0.3.297
curios version:
4.0.5.2

**Comment by P3pp3rF1y** [comment]
I will need the crash log for that

**Comment by P3pp3rF1y** [comment]
So the shift clicking into backpack works for me and I am sure for a lot of other people given how many download the mod and how common it is to have curios in modpacks. 
which means in your case something special is happening but to understand that better I need the crash log, otherwise I can just close the ticket

**Comment by P3pp3rF1y** [comment]
closing as no additional info was provided and just shift clicking into curios slot works in many different packs
