### ISSUE TITLE
Crafting Upgrade — Crash

### ISSUE THREAD

**Issue by JWTHDYTWA** [P3pp3rF1y/SophisticatedBackpacks#26]
Attempt to craft something in the Crafting Upgrade gui crashes the game.
[Crash report](https://gist.github.com/JWTHDYTWA/3a14e97da2cec6c5f1dc42410982202b)

**Comment by JWTHDYTWA** [comment]
1.2.1.127

**Comment by P3pp3rF1y** [comment]
This works correctly with SBP by itself or in the pack that I am playing at the moment - Enigmatica 6. So in your case it must be caused by a core mod that modifies vanilla logic, based on the crash log it seems to be unionlib - haven't tested it myself so to prove it is the mod you will need to remove and see if the issue persists. And then this issue needs to be reported to them as there nothing I can do to solve it.
