### ISSUE TITLE
Item Duplication

### ISSUE THREAD

**Issue by anthonyhab** [P3pp3rF1y/SophisticatedBackpacks#28]
**Describe the bug**
Item or stack gets duplicated when placing in 1st slot of the hotbar while using backpack.

**To Reproduce**

1. Empty your first hotbar slot.
2. Open backpack.
3. Place item in first hotbar slot.

You are kicked out of the interface and you will have a copy of the item on the ground.
It seems to work 50% of the time with this method.
If you have more than one of the item already, there is another method with better success rate.

1. Place one of the item in the first slot.
2. Open backpack.
3. Place the rest of the stack on the first slot.

You are then kicked off the backpack interface, half of the stack drops on the floor and upon opening the backpack again, it drops the other half.

**Versions**

**Mod Version:** 1.2.1.127
**Minecraft version:** 1.16.4
**Forge version:** 35.1.36
**Modpack:** Enigmatica 6 - 0.3.5

**Comment by P3pp3rF1y** [comment]
First of all this is fixed in the latest versions of the mod. Second the only issue in sbp was that the backpack gui closed when the first stack was changed. There is some other mod in enigmatica that didn't like this closing and duplicated the stack as I tried replicating that with just sbp and it would only close the backpack.
