### ISSUE TITLE
Custom support for Jukebox upgrade to play other modded discs

### ISSUE THREAD

**Issue by Wakatsu** [P3pp3rF1y/SophisticatedBackpacks#293]
So, some discs from other mods do play like normal, but then some don't. Examples that I encountered myself include:
1. Two discs from Aquamirae mod
2. Red disc from More Music mod
3. Pancakes from Supplementaries mod

1. Open backpack
2. Click on 'jukebox' tab
3. Try to insert any of the discs mentioned above
4. It won't happen

Expected behavior - disc would go into slot and jukebox would play corresponding music

Versions - Latest. I always update to the latest release, checking daily.

**Comment by P3pp3rF1y** [comment]
This is because those discs are actually not implemented as an extension of vanilla discs and thus they have to have a special implementation for each. And to support them in SBP I will need to add code that's able to play them. I will make this into an enhancement and look into it together with implementation for Etched mod.

**Comment by jaz000** [comment]
This does work for discs done properly. We use the MCDJ mod and we just had a zombie piglin spawn in playing Iron Maiden from his backpack :-)

My ask is can it be played on loop by default, he's gone quiet now which is less fun ...

**Comment by P3pp3rF1y** [comment]
in 1.21 there are now component based discs which can support custom discs and mods implementing that will have their discs automatically playable in sophisticated so I am closing this
