### ISSUE TITLE
[bug] Item dupe

### ISSUE THREAD

**Issue by LukeOnuke** [P3pp3rF1y/SophisticatedBackpacks#30]
## Description
A simple way to dupe items using backpacks from sophisticated backpacks.

## How to replicate
1. Take a backpack
2. Fill with any item
3. Hold q and wait for the backpack to drop
4. Whilst the menu is open take the items out
5. Pickup backpack
6. Repeat

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest version. It adds world saved data as a backing store for backpacks so it's impossible to duplicate inventory  there as any kind of item manipulation won't prevent saving the inventory to the correct spot from where it's open the next time. And I have also added a bit of code to close the backpack screen in case player drops a backpack like this just because it seems odd working with backpack's inventory while the actual item is on the ground in entity form
