### ISSUE TITLE
[BUG] Bug with EquipmentCompare

### ISSUE THREAD

**Issue by LunarFactory** [P3pp3rF1y/SophisticatedBackpacks#314]
**Describe the bug**
I attached screenshot. Check there please.
and also, checked with other mods, and there is no bug like this.

**To Reproduce**
1. Open backpack
2. Press shift to see backpack's inventory and compare

**Expected behavior**
Just working correctly.

**Screenshots**
![2021-11-23_18 51 30](https://user-images.githubusercontent.com/69113888/143003131-963ee069-66f5-417e-a0e2-4405746a788f.png)
(Sorry for korean,)

**Versions**
Mod version that you're using. Version of forge may also be helpful in some cases
sophisticatedbackpacks-1.16.5-3.11.1.390
EquipmentCompare-1.16.5-1.2.7

**Comment by LunarFactory** [comment]
#313 maybe same issue.

**Comment by P3pp3rF1y** [comment]
Alright this will need to be reported to EquipmentCompare, they don't seem to be compatible with forge's events that allow mods to implement their own handling of tooltips. 
I am not expert on mixins but it may be because both them and forge are adding functionality in the same part of vanilla code and I guess their doesn't get added to the correct part. Anyway they should be using what forge has ready for them instead.
