### ISSUE TITLE
Got this error when trying to shift click an arrow

### ISSUE THREAD

**Issue by Chrisjohnson57387** [P3pp3rF1y/SophisticatedBackpacks#34]
So my game crashed, and I got this error when trying to shift click an arrow from the left side of the backpack inventory.  That said, arrows were there because the backpack instantly took all my storage from my inventory, and only showed items in those left slots, so I was trying to see if I could take items back.

Edit: So after I crashed and logged back in, my items were back to me and the backpack didn't take them away again.

Edit 2: I'm using the version of backpacks 136, downloaded yesterday at what my computer says is an hour before you released a new version. I'm going to test out the same scenario in the new version and update this accordingly.

The game crashed whilst container click
Error: java.lang.ClassCastException: net.minecraft.item.ArrowItem cannot be cast to net.p3pp3rf1y.sophisticatedbackpacks.api.IBackpackUpgradeItem

**Comment by P3pp3rF1y** [comment]
That sounds like the backpack was in some kind of invalid state where it didn't have any slots at least on server side. I have seen this happen when I used mekanism cardboard box on backpack block which is actually something that was fixed in the latest version. 
Did you perhaps manipulate with the backpack using something like the cardboard box?

**Comment by Chrisjohnson57387** [comment]
Kind of I think. It happened first, then I sat it on a cabinet added by the Otaku mod. Then when I tried the action, crash. 

Though, update has solved my woes.
