### ISSUE TITLE
Cannot Auto Stack using Quark

### ISSUE THREAD

**Issue by SickMcNugget** [P3pp3rF1y/SophisticatedBackpacks#351]
**Describe the bug**
Cannot use the Quark auto-stack feature inside backpacks

**To Reproduce**
1. Open backpack
2. Hold Shift / click the lock button
3. Insert and extract buttons do not turn yellow (auto-stacking is disabled)
Note that this is the same for in-inventory and placed backpacks

**Expected behavior**
The icons should turn yellow and allow autostacking to and from the backpack.

**Screenshots**
![image](https://user-images.githubusercontent.com/3212055/146414303-391dd958-e3dd-4eb9-9cf8-abd27d3401d5.png)
![image](https://user-images.githubusercontent.com/3212055/146414775-d318d00f-a6c8-4cca-b982-5cb08e0217bb.png)

Direct your eyes to the down and up arrow icons. As you can see they do not light up yellow when the inventory selected is a backpack.

**Versions**
Minecraft 1.16.5, forge 36.2.20, Sophisticated Backpacks 3.12.2.432

**Comment by P3pp3rF1y** [comment]
So Quark has very bad interaction with some of the SBP features that used to cause item loss and dupe bugs that's why I am replacing their buttons with implementation that's compatible with SBP and preventing Quark to be able to interact with any of the slots as keybinds would still run their logic and cause these bugs. I will take a look at this if I could add logic on my side but I am suspecting this won't be easily possible in which case I will just close as not to be fixed.

**Comment by P3pp3rF1y** [comment]
I am starting to focus much more on 1.18 and in there Quark is an optin and I will need to provide different implementation than in 1.16.5. so I am closing this and in 1.18 will add new Quark compat overall
