### ISSUE TITLE
backpack deleted items when unstacking inside it

### ISSUE THREAD

**Issue by BamsyTheSergal** [P3pp3rF1y/SophisticatedBackpacks#371]
**Describe the bug**
pressing shift + middle mouse deleted all items except
stuff that was above 64 with the stack upgrade tier 2

**To Reproduce**
(works in multiplayer and singleplayer)
1. Open backpack
2. have battery upgrade, stack upgrade tier 2
3. press shift + middle mouse
4. See bug of deleted stuff

**Expected behavior**
maybe give a error saying that you can't unstack?

**Screenshots**

How many stacks it needs to cause it.
![javaw_Qp075z5q01](https://user-images.githubusercontent.com/12705993/147714445-71b1a3ba-95b3-41b4-b608-f57d91c5e9ba.png)

after pressing shift + middle mouse
![javaw_y4eNd0NC4O](https://user-images.githubusercontent.com/12705993/147714474-069db3ec-ea20-4921-90ca-74215b72dc8d.png)

**Versions**
game version: 1.18.1
mod version: 3.14.3.485
forge version: 39.0.9
modpack/version: all the mods 7 0.2.13

**Comment by P3pp3rF1y** [comment]
so Shift - middle click does nothing with sbp and forge only so I will need to understand what mod / functionality you have (shift middle click or just middle click linked to) but it's very likely it's some sort inventory mod and that's the cause of your issue here.

**Comment by BamsyTheSergal** [comment]
> so Shift - middle click does nothing with sbp and forge only so I will need to understand what mod / functionality you have (shift middle click or just middle click linked to) but it's very likely it's some sort inventory mod and that's the cause of your issue here.

i am assuming its one of the inventory tweaks mods, because i am using the All the Mods 7 modpack.

it gave no error in the console of the server/client too.

these two add middle click sorting that is in the pack.
https://www.curseforge.com/minecraft/mc-mods/inventory-essentials
https://www.curseforge.com/minecraft/mc-mods/inventory-sorter

**Comment by P3pp3rF1y** [comment]
Inventory Essentials actually doesn't do any sorting so the issue here is with Inventory Sorter. And from my testing with the mod I can see that with default keybind to sort backpack being set to middle click there's no issue so in your modpack that must be set to a different key and that's why you're having this issue. Just set the sort backpack keybind to middle click again and you're all set. It's not going to conflict with any other keybind as it only works if player middle clicks in the backpack's inventory, in all the other cases it let's other key handlers to take care of the key handling.

**Comment by SuperKael** [comment]
I can confirm that this DOES still happen in the All the Mods 7 modpack when shift-middle-clicking in the backpack. It will occur so long as Inventory Sorter's sort button is bound to Middle Button, even if Sophisticated Backpack's sort keybind is also set to Middle Button.
