### ISSUE TITLE
[1.18.1 - 3.15.1.505] Dupe - Stack Upgrade

### ISSUE THREAD

**Issue by Salamance73** [P3pp3rF1y/SophisticatedBackpacks#396]
When using the stack upgrade it is possible to put two inventory-holding items that allow for GUI based insertion in the same slot (bundles in my case but I think shulker boxes can do this.) This allows for any item to be put into both inventories at the same time. After splitting those two bundles you have two copies of the same inventory. 

Bundles stacked, empty:
![image](https://user-images.githubusercontent.com/26430914/148891815-debd8628-4f37-476a-a723-afd0775f51a2.png)

Bundles stacked, item inserted:
![image](https://user-images.githubusercontent.com/26430914/148892264-0aa2ce69-67b4-41cb-83f2-22a5d4e9ed24.png)

Bundles unstacked, both holding the original item:
![image](https://user-images.githubusercontent.com/26430914/148892340-1bc773ff-55b8-4425-95f6-93358b561676.png)

**Comment by P3pp3rF1y** [comment]
So a few things here:
- the insert through gui is only possible with quark and because quark doesn't check stack size it will happily insert the item into stacked container so this will likely affect any mod that allows stacking of non stackable items
- to handle this on SBP side you can use `nonStackableItems` config and provide list of containers like this that shouldn't stack
- or if you don't want them to go into backpack altogether you can use `disallowedItems`
