### ISSUE TITLE
The thing about your Liquid XP

### ISSUE THREAD

**Issue by ZEROX7** [P3pp3rF1y/SophisticatedBackpacks#427]
hey there so your liquid xp that you add could you eather adda abucket and a world fluid too or make it so that i can config to use another mods version of it? because i ran into some issues if i have like tanks that can store it i can take it out but it cets void for example in a refined storage fluid grid for example

**Comment by Bazyliii** [comment]
Yeah, that would be great!

**Comment by Twisted-Code** [comment]
What info do you need here? I think they were asking if you could add a "bucket of liquid XP" (or whatever you want to name it) so that other mods which expect any given fluid to have a bucket form are not confused by the lack of a bucket form. I don't know anything about the fluid-deletion issue described above, but I've def had issues with this when trying to use fluid filtering mechanics. I forget which mods, but I know for a fact LaserIO doesn't support storing fluids in its filters; it stores an item and gets the fluid from that if applicable (i.e. depending on what interface the filter card is in). And tbh I would like to be able to transport xp in a bucket regardless of such technicalities.
That said, I presume you would've rather this issue be opened on SophisticatedCore's tracker since it's Core that adds the fluid if I'm not mistaken (I think chests can also have the XP upgrade)? Maybe I will reference this issue over there after I open the suggestion/issue I originally came here to open.

**Comment by P3pp3rF1y** [comment]
in 1.21 there's better support for setting fluid filters and xp bucket as well so closing this
