### ISSUE TITLE
[Bug/Mod Compatibility] Corail Tombstone not removed backpacks from Curios Slot on death.

### ISSUE THREAD

**Issue by FryoKnight** [P3pp3rF1y/SophisticatedBackpacks#429]
**Describe the bug:**
When this mod and the mod [Corail Tombstone](https://www.curseforge.com/minecraft/mc-mods/corail-tombstone) are used together, Backpacks are not removed from the [Curios](https://www.curseforge.com/minecraft/mc-mods/curios) Back Slot, remaining in the slot after death, even though other Curios from other mods are removed.

**To Reproduce**
1. Have all mentioned mods installed
2. Have Backpack in Back Slot
3. Die.
4. Back remains

**Expected behavior**
Backpack should be removed from inventory and stored inside of the Gravestone (unless enchanted with Soul-bound enchantment or similar mechanics).

**Versions:**
Forge - 39.0.76
Curios API - 5.0.6.1
Sophisticated Backpacks - 3.15.9.533
Corail Tombstone - 7.4.1

**Comment by FryoKnight** [comment]
This will also be cross-posted to Tombstone's issue tracker.

**Comment by bbgott** [comment]
This same behavior appears to be happening with the gravestone mod.  The backpack is not being removed from the curios slot and placed in the grave

**Comment by P3pp3rF1y** [comment]
To be honest I have no idea why this would be happening, certainly there's no code in SBP that would take care of keeping backpack on player in any slot which means there's nothing for curios either. I will need to debug to see what exactly are these gravestone mods doing there and how that may cause some incorrect interaction here.

**Comment by P3pp3rF1y** [comment]
I am unable to recreate this so I will need exact steps to recreate and no they are not the ones described in the description as using those the backpack gets removed from player. Or perhaps you thought that it stays on player because when you collect your grave the backpack gets automatically put into its curios slot?

**Comment by bbgott** [comment]
After doing some testing, with just Sophisticated Backpacks, Curios and the gravestone mod it removes the backpack as expected.  When adding Botania to the mix, that's when the backpack doesn't seem to get removed.

MC: 1.18.1
Forge: 39.1.0
Botania: 1.18.1-429
Curios: 5.0.6.2
Gravestone: 1.0.2
JEI: 9.2.1.69
Patchouli: 1.18.1-65
Sophisticated Backpacks: 3.15.9.533

Without Botania and Patchouli, things work as expected.  With those 2 mods then the backpack stays on the player after death

**Comment by bbgott** [comment]
The same behavior exists with corail tombstone.  With botania in the pack, the backpack is not removed from the player.  Without botania in the pack, the backpack is removed and stored in the gravestone as expected

**Comment by P3pp3rF1y** [comment]
This appears to be a botania issue - once botania is in the pack curios can't access its inventory when the player dies and because of that can't drop any curio items, not just the backpack but also any curio items that botania adds. So please report to them. Also from my testing it appears to be 1.18 issue only as the backpack dropped properly in 1.16.5.

And yeah I actually recreated the issue without any grave mod in the pack as it also affects just simply dropping the items when there's no grave mod in.
