### ISSUE TITLE
Undyeable backpacks with a custom modpack in multiplayer (1.18.2)

### ISSUE THREAD

**Issue by Snooziepup** [P3pp3rF1y/SophisticatedBackpacks#463]
**Describe the bug**
On a multiplayer dedicated server, dyes cannot be applied to backpacks with these mods
the backpacks are dyeable as normal on singleplayer with the same mods
[server_log.log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/8616904/server_log.log)
client log: https://paste.ee/p/9bNqi
modpack: https://drive.google.com/file/d/1eTQ88g6zh9Rt9lagYf67qPiHsTCbaSOr/view?usp=sharing

**To Reproduce**
Join a server with the given modpack,  attempt to apply dye to a backpack on a crafting table

**Expected behavior**
The dye should be applied to the backpack

**Versions**
3.15.18.570

**Comment by P3pp3rF1y** [comment]
Sorry but I don't have time debugging random modpacks. If you can tell me what's the minimum set of mods that still creates this issue I can take a look but otherwise you will have to figure it out yourself. Sounds like some mod is adding recipe that conflicts or something messing with dyes on server.

**Comment by P3pp3rF1y** [comment]
There was no additional info provided here and dyeing backpacks works so I am going to close
