### ISSUE TITLE
Adv. Compresor "Match Tag" filtering can't add item

### ISSUE THREAD

**Issue by xchoice** [P3pp3rF1y/SophisticatedBackpacks#473]
**Describe the bug**
There are many blocks that cannot be added to the filter, an example is iron bars(minecraft:iron_bars).

**Conflicting mods**
To follow the iron bars example, Quark. The thing gets compressed into iron grates(quark:grate)

**To Reproduce**
Try to place iron bars in the item slot of the filter.
The item does not go into the item slot, and remains in the cursor.

**Versions**
backpack 3.15.18.570
core 0.0.5.12
forge 40.1.15

**Comment by P3pp3rF1y** [comment]
why should iron bars go in there? in vanilla they are 3x2 recipe and those are not supported - only 2x2 and 3x3

**Comment by xchoice** [comment]
to blacklist or whitelist the block from being compressed in modded environments. Also...it doesn't go into ANY match tag filter.
Not even the pickup or magnet.
![image](https://user-images.githubusercontent.com/4960673/169166845-e5048b82-0463-4401-b3ee-4f56efdd3b5e.png)

**Comment by P3pp3rF1y** [comment]
well there's nothing to blacklist if it can't be compressed by compacting upgrade so that's why it can't go in the filter and the reason it can't go in tag filter is because it doesn't have any tags in vanilla for sure. Unless of course the modpack you have adds tags to iron bars in which case that would be an issue that will require fixing, but the only condition that's used there is just a quick check to see if the item has any tags at all if it doesn't it can't be put in that slot.

So unless you have any additional info here all of this so far is working as it's supposed to and I am going to close the ticket soon

**Comment by xchoice** [comment]
maybe I do not understand, but isn't minecraft:iron_bars  the tag for it? like say.... forge:gems? or they are different?

**Comment by P3pp3rF1y** [comment]
minecraft:iron_bars is the item name. Tags are assigned to items on top of this to put them into groups of things that can then be referred to. So minecraft:diamond and minecraft:emerald have forge:gems tag.

**Comment by xchoice** [comment]
so because they don't have a tag they can't be filtered by "match tag" :S?

**Comment by P3pp3rF1y** [comment]
well yes, because there's no tag to filter on. You can still filter for tag not being present which will match the bars for sure because they don't have any. 
If there isn't anything else here I am going to close as this is working as expected

**Comment by P3pp3rF1y** [comment]
closing the ticket as this works as expected
