### ISSUE TITLE
Inventory Sorting doesn't sort well with the stack upgrades, and can even delete items

### ISSUE THREAD

**Issue by massacring** [P3pp3rF1y/SophisticatedBackpacks#493]
**Describe the bug**
When you try to sort using the inventory sorting mod and have any of the stack upgrades, the backpack sorts into normal stacks of max 64. If you have more items than slots in the backpack after this sort, the last ones in the sorting will be deleted.
I had a 4 stacks of cobble, planks, logs, sticks, redstone, iron and multiple stacks of many other things, when I accidentally sorted using inventory sorting as a muscle reflex. The result was that half of my non-stackable items that would usually sort last got deleted.

**To Reproduce**
1. Open backpack
2. Apply the stack upgrade.
3. Fill the backpack with more individual stacks than slots in the backpacks inventory.
4. Use inventory sorter on the backpack, and the excess items will be deleted.

**Expected behavior**
I would expect the items to fall on the ground or transfer into my inventory, since I assume you have no way of stopping the sorting from happening to begin with as you didn't make the inventory sorter mod.

**Versions**
sophisticatedbackpacks-1.18.2-3.16.4.584
sophisticatedcore-1.18.2-0.1.0.19 (dunno if it's relevant but it's in the pack)
inventorysorter-1.18-19.0.0
I'm playing on the FTB Presents Direwolf20 1.18 modpack, I know I'm supposed to check the mods by themselves but I honestly can't imagine it would change anything given the context of the bug so I chose not to waste my time.

**Comment by P3pp3rF1y** [comment]
InventorySorter needs to be disabled in sophisticated screens for this to not happen. I am actually automatically trying to disable it, but because of bug in inventorysorter this is not working https://github.com/cpw/inventorysorter/issues/119 

Best way to prevent this is to make sure that you have sorting in backpack and storage mapped to the same keybind as inventorySorter (middle click by default) in which case sophisticated sorting will be the default sorting used and you won't see these issues. The other way is to disable sophisticated screens in InventorySorter configs
