### ISSUE TITLE
Advanced Restock upgrade does not work with Storage Drawers

### ISSUE THREAD

**Issue by LuciusV** [P3pp3rF1y/SophisticatedBackpacks#510]
**Describe the bug**
Advanced Restock upgrade does not work with Storage Drawers - shift+rightclick opens Storage Drawers GUI instead

**To Reproduce**
1. Insert Advanced Restock upgrade, filter to dirt (or anything else)
2. Shift+rightclick on drawer with dirt
3. See drawers menu opening instead of filing backpack

**Expected behavior**
Backpack is filled with dirt from drawer.

**Versions**
sophisticatedbackpacks-1.16.5-3.15.7.531
StorageDrawers-1.16.3-8.5.1

**Comment by P3pp3rF1y** [comment]
I have only got to this now and tested it in 1.18. I am unable to recreate and restock works as expected. A quick thought is that you need to have the backapack in your hand or you need to press an inventory interaction key that you have set in controls and it's not obvious to me that you have done either of those. 

if you still care about this I will need more info on how to recreate otherwise I am going to close

**Comment by LuciusV** [comment]
Thank you for mentioning interaction key - with it and with backpack in hand it works as expected.
