### ISSUE TITLE
Sophisticated Backpacks being overwritten

### ISSUE THREAD

**Issue by KyriAmaranth** [P3pp3rF1y/SophisticatedBackpacks#537]
On Server, upon death of a player, the players backpack has been overwritten by a living players backpack.

Possibility of it being an interaction with either the curio mod or corail. havent done any testing on it yet.

Verision 
sophisticatedbackpacks-1.18.2-3.17.9.616
forge-1.18.2-40.1.31

**Comment by P3pp3rF1y** [comment]
I don't know of a way that this could happen other than the player having a backpack with UUID that's the same as another player's UUID - backpack either cloned in creative or gotten through some way which duplicates the UUID. If you know which player's contents you're getting in your backpack you can check those backpacks with advanced tooltip (F3 + H)

Otherwise I will definitely need more info here on how to recreate as this is such a common case that if it was really happening to more players I am sure I would have heard about this a lot by now.

**Comment by KyriAmaranth** [comment]
Yes found out the backpacks managed to get the same uuid.  As far as I know these were not creative spawned in anyway.
Also during testing of this found that picking up and placing the backpacks in your inevtory changes the uuid of it everytime.  Dont know if that is intended or a bug.

**Comment by P3pp3rF1y** [comment]
I believe you came from ATM camp, right? There's some mod in ATM which makes backpacks get uuid assigned when they are just in JEI and in the past also as a result of crafting the basic backpack. That's an issue that I have added a change for to basic backpack recipe back about a month or two. But if the backpack was crafted before then it could have gotten the uuid assigned like this. Are you perhaps playing that long?

**Comment by KyriAmaranth** [comment]
The backpack was crafted yesterday. And yes it is from ATM

**Comment by P3pp3rF1y** [comment]
the only thought i have in that case is that the way it was crafted skipped logic in the basic recipe that removes the uuid on craft. But to be honest to be able to do anything with this ticket I will need info on how to recreate crafting backpack with already existing uuid / one that you can see somewhere even before you take the backpack out of the crafting slot

**Comment by KyriAmaranth** [comment]
Im not the one who crafted them, so i unfortunately dont know.

**Comment by P3pp3rF1y** [comment]
alright given the the lack of info I am going to close as this very much sounds like there was a dupe bug in crafting / drop or duplicated using creative mode and there's nothing I can do about those
