### ISSUE TITLE
Dupe with backpacks and corail tombstone (could also be any grave mod i assume)

### ISSUE THREAD

**Issue by LuciferFX** [P3pp3rF1y/SophisticatedBackpacks#538]
**Describe the bug**
I was playing on a server and i died like 5min or so from a crash and the crash rolled server back 5 min and when i spawned into server i was near where i died and had all my stuff on me and my grave infront of me will all my stuff (aka duped my stuff)

This led to me getting a 2nd backpack with exact same stuff and now when i have 1 backpack in my backpack slot and 1 in top row of inv (or anywhere in inv) and open backpack on my back to put stuff in or update whats in the backpack all that stuff also updates in the other one and i can take all the stuff from the backpack in my inventory and it does not change contents of backpack in slot.

**To Reproduce**
Server crash with rollback (maybe)
1. Open backpack on backpack slot
2. Update contents
3. go to other backpack
4. Duped items

Video:

https://user-images.githubusercontent.com/82917572/179423792-1eefb697-3db4-4228-b406-b8a481146b73.mp4

**Versions**
sophisticatedbackpacks-1.18.2-3.17.10.621.jar

**Comment by P3pp3rF1y** [comment]
there's nothing I can do about this one. it's really the crash that causes the issue so you need to prevent the crash. And there definitely was a rollback on the contents of the player inventory otherwise you wouldn't have the backpack in grave and on the player at the same time or the grave mod failed to remove the stuff from player. 

Anyway nothing for me to take care of.
