### ISSUE TITLE
Backpack with same UUID when upgrading

### ISSUE THREAD

**Issue by xalixilax** [P3pp3rF1y/SophisticatedBackpacks#580]
**Describe the bug**
I'm currently on TNP limitless 5 
I got a bug where for the past 2 login, 2 of my backpack got the exact same inventory at login. Losing all of the progress and the items that were process and moved during the play session. On further inspection the 2 backpack got the exact same UUID

**To Reproduce**
It's a bit hard to really explain how it happen since I'm not 100% sure but some of the process is.
Upgraded a backpack from a backpack (with the upgrade) from gold to diamond using JEI ( Key U ) and for some reason it moved a backpack from my inventory to the crafting inventory. I think the crafting inventory was IN the backpack I tried to upgrade. 
Next login, both backpack had same inventory resulting in item duplication

It look like that inventory even reset when I move the backpack. I just removed all the item and moved it for the screenshot and all the items reappeared.

I wish I could be more precise but I can't really tell much more. I tried to replicate in creative but the other backpack didn't seem to automatically be used for the crafting result while I could still do it in survival

**Expected behavior**
No duplicate UUID

**Screenshots**
![image](https://user-images.githubusercontent.com/2474569/184515438-52b5b887-1c99-4ec6-94c9-0fb611f9884b.png)
![image](https://user-images.githubusercontent.com/2474569/184515439-bf1401b8-4c95-47cd-80fd-6c64f5a39d34.png)

**Versions**
1.18.2-3.18.16.671

**Comment by xalixilax** [comment]
I tried to move the items to get rid of the backpack. I cannot delete the 3 auto smelting upgrade. They key coming back in my inventory of they get duplicate until I have 3. If it could be helpful, I could make a video.

**Comment by P3pp3rF1y** [comment]
Based on steps you have described I am always only ever able to create backpacks with unique UUID. So will need steps how to recreate otherwise the only thought I have is that these two backpacks had the same id even before. The other stuff you're describing that's happening to you are just symptoms of the same UUID.

**Comment by enjoyable1** [comment]
> Based on steps you have described I am always only ever able to create backpacks with unique UUID. So will need steps how to recreate otherwise the only thought I have is that these two backpacks had the same id even before. The other stuff you're describing that's happening to you are just symptoms of the same UUID.

hey！I also had an incident where the same uuid was generated, and when the player was killed by him, people nearby would get the same uuid.  Empty packs will be given or modified as dead players' packs;  This resulted in many copies of the dead player's backpack, and the items in it were also independent.  It was not known how to stabilize the trigger, but this problem was repeated many times.  I don't think there should be two UUids in the whole world.

**Comment by P3pp3rF1y** [comment]
@enjoyable1 there's no reliable way for me to tell that two backpacks with the same UUID exist unless they are both in player's inventory, potentially I could be checking all players but that logic would eat valuable processing time even if players were not using any backpack at all. As for your experience the only thing I can tell is that I don't have any triggers happening when player dies so some other mod must be interacting here and trying to do something with player's inventories in general - perhaps graveyard mod that doesn't approach this correctly and instead of polling just an inventory of the player that died it is going through inventories of every player online??

**Comment by enjoyable1** [comment]
> @enjoyable1 there's no reliable way for me to tell that two backpacks with the same UUID exist unless they are both in player's inventory, potentially I could be checking all players but that logic would eat valuable processing time even if players were not using any backpack at all. As for your experience the only thing I can tell is that I don't have any triggers happening when player dies so some other mod must be interacting here and trying to do something with player's inventories in general - perhaps graveyard mod that doesn't approach this correctly and instead of polling just an inventory of the player that died it is going through inventories of every player online??

Thanks, it may have been copied before it was used, but I used the plugin to distribute a backpack to players.  Maybe that's the reason.  Or could it be Authme?  Or keepinventory true?  My idea is that if the tag data is not restored correctly and is incorrectly processed by additional plugins, I will try my best to experiment and let you know if there is any new progress.  My friends and I have so many mods that I can't find out who caused them.

**Comment by P3pp3rF1y** [comment]
I added deduping logic quite some time ago which automatically checks all online players' inventory looking for duped UUID and dedupes it so this should no longer be valid with any versions released this year. thus closing the issue
