### ISSUE TITLE
Inventory Sorter Deleting Items (Sometimes)

### ISSUE THREAD

**Issue by Legoman9571** [P3pp3rF1y/SophisticatedBackpacks#595]
**Describe the bug**
Using Inventory Sorter by cpw on the backpack sometimes deletes items, it doesn't seem consistent however as it doesn't always do it. I've yet to find out what the exact conditions to reproduce are.

**To Reproduce**
1. Open backpack
2. Middle mouse to sort with sorter
3. Items disappear into void (sometimes)

**Expected behavior**
Sort and not delete items

**Versions**
Minecraft Version: 1.18.2
Forge: 40.1.74
Inventory Sorter: 1.18-19.0.0.
Sophisticated Backpacks: 1.18.2-3.18.24.704

**Comment by P3pp3rF1y** [comment]
The only thing I can say here is that you need to either blacklist backpack screen in inventory sorter so that it doesn't try to sort it or make sure that SB sort inventory control is set to middle click as well.

There's an integration I have added for inventory sorter specifically but it's not working because of bug described here https://github.com/cpw/inventorysorter/issues/123
