### ISSUE TITLE
Backpack item insertion bug

### ISSUE THREAD

**Issue by Gumatan** [P3pp3rF1y/SophisticatedBackpacks#635]
**Describe the bug**
Backpacks with stack upgrades places some newly inserted items in new slots instead of the existing item slot.
(It seems to only occur with pipez pipes inserted items. Mekanism pipes or create funnels seems to work fine)

**To Reproduce**
1. Place a backpack with stack upgrades
2. Connect the backpack to a pipez item pipe
3. Insert multiple kind of items in the backpack using the cable

**Expected behavior**
I expect the inserted items to be added to the count of the existing stack, not placed in a new slot

**Screenshots**
https://www.youtube.com/watch?v=cvEo1bP06t0

**Versions**
Minecraft : `1.16.5`
Forge : `36.2.39`
Modpack : Blackstone block [1.0.5](https://www.curseforge.com/minecraft/modpacks/blackstone-block)
Sophisticated backpacks : `3.15.19.721`
Pipez : `1.2.15`

The Bug stared occuring when upgrading the modpack from `1.0.4` to `1.0.5` In this modpack upgrade sophisticated backpacks was upgraded from `3.15.15.607` to `3.15.19.721` and the pipez version stayed the same

**Comment by P3pp3rF1y** [comment]
Looks like a mod is adding capability data to those stacks and the reason you're seeing it with the newest version is because then it started considering capability data when deciding if two stacks are the same.
I will need to understand what mod is adding these or rather with what minimal set of mods this is happening so that I can take a look at whether that's even solvable on my side.

**Comment by P3pp3rF1y** [comment]
closing this one, it's a known issue in 1.16.5 that I can't fix and that version isn't supported anymore either
