### ISSUE TITLE
not stacking

### ISSUE THREAD

**Issue by pnwadike** [P3pp3rF1y/SophisticatedBackpacks#639]
**Describe the bug**
Sophisticated backpack not stacking on pick up. Whenever I pick something up with any of my back pack, instead of going into an incomplete stack, it just starts it’s own stack. This just randomly started one day. Ex the roses and the carrots

**Versions**
sophisticatedbackpacks-1.16.5-3.15.19.721

![bao9m0cdo8z91](https://user-images.githubusercontent.com/117968048/201271609-f8885c0d-8684-4acc-b7af-e526bb1ac459.jpg)

**Comment by X-Niter** [comment]
Versions
sophisticatedbackpacks-1.16.5-3.15.19.721

![backpack](https://user-images.githubusercontent.com/30506033/202055359-fa0931ab-d201-4c68-bed1-3c7d4be67c5d.png)

Only with using the pickup upgrade**
They pick up items as usual but they don't automatically condense stacks which makes it so the backpack fills up with individual stacks of 2 items each.

Once the backpack is filled up, is then begins to put the items into the players inventory instead of stacking the items in the bag.

I had one user mention that he got lucky and saw that some stacks were filling up still while other were not which then the items went into the players inventory.

Meanwhile, we found ways to get around this, you can use a stack upgrade which then it is fine so long as you use the stack upgrade.

**Comment by X-Niter** [comment]
![image](https://user-images.githubusercontent.com/30506033/202056161-ef0c628e-643e-4e14-b393-8a076e52b938.png)

There also looks to be a very slight chance of this happening with a magnet upgrade, but not as much.

**Comment by P3pp3rF1y** [comment]
That looks like some mod is adding capability data to those stacks. Would be good to understand with what mod this is happening.

**Comment by X-Niter** [comment]
I see, um, I don't know how fast I might find that, but I'll try to keep my neck out for it.
This is technically happening on a modpack made by folks [E6E], so what I might do is allow the main creators of the pack to get some traction on this as they too would have an in-depth understanding and even an idea to assist us all here.

**Comment by tinypanda31** [comment]
> That looks like some mod is adding capability data to those stacks. Would be good to understand with what mod this is happening.

This issue was happening to me as well in Ragnamod VI, so ill link the two of you up.  I thought it had something to do with the mining laser but looking at the other sc's in this thread it seems to be something else.
Edit: https://www.curseforge.com/minecraft/modpacks/ragnamod-vi/issues/1268

**Comment by Richfly01** [comment]
Fairly certain its Sophisticated, as I just put in a older version and it works fine.

**Comment by P3pp3rF1y** [comment]
This should now be resolved with the latest version uploaded to curseforge that is just in review by CF.

**Comment by darchitectlp** [comment]
Sorry to raise this again, but I'm having the exact same issue with sophisticatedbackpacks-1.16.5-3.15.20.755.jar. Any chance you can peek at the issue again? Also, it appears that the backpack (with the magnet upgrade) cannot pick up items if the player's main inventory is full.
