### ISSUE TITLE
better filtering on advanced pickup/magnet upgrades

### ISSUE THREAD

**Issue by hvdklauw** [P3pp3rF1y/SophisticatedBackpacks#66]
I think two things would make it better:

- tag filtering: select per item which tag(s) to use, now items have multiple tags and some are relevant but a lot are not.
- Contents filtering: Filter based on what is already in the backpack

**Comment by P3pp3rF1y** [comment]
I have the filtering by backpacks implemented in dev (I was already working on that at the time this issue was posted). 

But as far as filtering by specific tag goes I don't really see a good/easy way of allowing player to select the tag and then also easily display which tag is actually selected in the list of filters. If you have any suggestions let me know.

But I also feel this is specifically aimed at valid_apiary tag being added to a lot of stuff and especially with nonblock items that doesn't seem to make much sense to me and should really be resolved somewhere else.

**Comment by hvdklauw** [comment]
Yeah, that's part of the problem yeah.

Filtering on specific tag is tricky, you would almost need a extra GUI where you can maybe just type out the tags you want, much like Mekanism digital miner does. But then it might have to be another upgrade to the advanced versions or a separate one altogether.

Another example is the create attribute filter, but that goes even further in some ways.

**Comment by P3pp3rF1y** [comment]
closing this as filtering by backpacks is in and there's better selection for filtering by tags as well
