### ISSUE TITLE
Auto-feeding upgrade doesn't work with Botania's Fruit of Grisaia

### ISSUE THREAD

**Issue by RigbyCoal** [P3pp3rF1y/SophisticatedBackpacks#685]
The auto-feeding upgrade doesn't see the Fruit of Grisaia from Botania as a food item, and thus isn't able to automatically feed the player when hungry/hurt, and you cannot use it on the filter either.

1. Open backpack
2. Click on Auto-feeder/Advanced Auto-feeder tab
3. Try to put the Fruit of Grisaia (with mana accessable in inventory) in the filter (any filter) or be hungry 
4. Does not recognize it as food in the filter/will not feed the player with the Fruit of Grisaia

I expected it to be treated as food but I assume it isn't counted as food due to the fact that it uses mana (Botania's main power/fuel/magic juice) in order to feed the player, and it doesn't technically get eaten (the player just chews on it but it doesn't disappear).

Minecraft version 1.18.2, Forge version 40.1.86, Sophisticated Backpacks version 3.18.35.752

**Comment by P3pp3rF1y** [comment]
That's because that one isn't actually a food but special item which gives player hunger. Looking at the code even adding a special compatibility would be at the very least difficult if not impossible because of how it drains mana while player is eating so no this is not going to work with feeding upgrade.
