### ISSUE TITLE
Sort does not combine memory slot stacks with non-memory slot stacks

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/SophisticatedBackpacks#686]
This happens with the sophisticated backpacks "sort backpack" keybind. Sorting does not combine the two copper stacks (and gold, lead, etc...), but I can combine them normally if I manually drag and drop the items onto the same stack. The top copper and lead stacks are memory-slot enabled, and if I disable memory slots the stacks sort (and stack automatically normally). 

maybe related or perhaps a separate issue: on occasion the magnet will pickup items and create a brand new stack, ignoring the memory slot items. I can't get it to happen consistently but it occurs fairly frequently.
![image](https://user-images.githubusercontent.com/47757354/212494902-3865eead-a176-467d-92bf-9af18513c3e9.png)

after removing memory slots, sorting appears to work as intended: 
![image](https://user-images.githubusercontent.com/47757354/212495044-96d92965-41d5-4879-9112-0fb9c028ec42.png)

however, magnetting up more iron still does not stack properly - or consistently. I mined 11 iron and 10 of it went into a stack and 1 created a new stack, although clicking sort does properly recombine these items:
![image](https://user-images.githubusercontent.com/47757354/212495233-b9a3c97c-d805-4f88-862f-7b8789f20cc7.png)

**Comment by P3pp3rF1y** [comment]
I am guessing this is 1.16 where there's an issue with some mod attaching data to stacks which makes them unstackable on magnet / pickup but they are again stackable once sorted in the backpack. 

And as for memory slots not sorting stacks into them - it's intentional that memorized slots don't sort as this could mean sorting stacks out of memorized slots and memory slots take new stacks as a priority so realistically you will only get stacks outside of memorized slots if you have moved them out of memorized ones or newly marked completely different slots as memorized or like in the case of 1.16 these stacks are different than the memorized ones.

**Comment by P3pp3rF1y** [comment]
Closing this as sort works correctly and there's #706 created for the stacking issue
