### ISSUE TITLE
sophisticatedbackpacks-1.16.5-3.15.20.755 magnet upgrade items don't stack right in the bag

### ISSUE THREAD

**Issue by darchitectlp** [P3pp3rF1y/SophisticatedBackpacks#699]
Install magnet upgrade (either tier) and it pull items in... BUT it puts like, two in a stack and then starts a new stack.

**Comment by Darkllightz** [comment]
Question: Does your mod pack or whatever have the mod "Item Filters" in it? Because I'm having the same issue and I've seen this issue floating around here. This issue is super frustrating and I'm trying to pin down what's doing it because it makes using the auto-pickup upgrade unusable. For a more specific instance, I'm using the mod pack Roguelike Adventures and Dungeons 2: version 1.0a
![image](https://user-images.githubusercontent.com/125032818/218090150-1f9a9eaf-6033-45e5-872a-2dadd7ec4b2d.png) 
![image](https://user-images.githubusercontent.com/125032818/218090982-8ad7ba8e-a12b-4467-a7df-740960c6a142.png)
![image](https://user-images.githubusercontent.com/125032818/218091178-ae5be070-aa56-4920-b5eb-8c6fa27f1f44.png)

As an example, here you can see that for some reason the cobble refuses to go into the memorized stack (which is the one located above the logs), for some reason dumps next to the sapphire, and then after that proceeds to make stacks of two infinitely. The in-mod sort button does not stack them for you. Somehow, the tags are exactly the same, so I don't have any idea as to why they refuse to stack together. If you drop items that were previously in your inventory and re-pick them up, they will correctly sort. If you'd like a list of all the mods I can provide that.

**Comment by darchitectlp** [comment]
I *DO* have Item Filters installed. Will try to boot up a session without it and see what happens.

**Comment by P3pp3rF1y** [comment]
this is an issue of some mod attaching so called "capability nbt" to stacks which makes them different at the time of pickup, but then that nbt somehow disappears. I am going to leave only the latest issue on this open, if you can find out what mod is causing this (or are able to recreate with just SB) I may still fix this though I don't support 1.16 version for quite a while now.

Please add info here #706
