### ISSUE TITLE
removing tak upgrade with shift causes inventory bug

### ISSUE THREAD

**Issue by czychuuu** [P3pp3rF1y/SophisticatedBackpacks#716]
**Describe the bug**
When you shift click tank upgrade backpack and player's inventory bugs out

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Open backpack
2. put tank upgrade
3. Shift click to remove the tank upgrade

**Expected behavior**
Tank upgrade removed normaly 

**Screenshots**
https://youtu.be/WFzPvr_ohZw

**Versions**
1.18.2-3.18.29.718 forge

**Comment by P3pp3rF1y** [comment]
Just retested and I am unable to recreate in dev so it's likely another mod in your modpack that causes some incorrect interaction. Could you retest with just SB / find out which mod that is? I can take a look and see if there's anything I need to fix.

**Comment by LogicEngineer** [comment]
@P3pp3rF1y
This bug is alive and well in 1.19.2. Let me know if you have any addition questions or need any additional info beyond what is below.

**Describe the bug**

Shift+Clicking the tank upgrade out of a backpack renders all inventory slots blank including the player's and the backpack itself is rendered in the top-left, in what is not visually a slot. Left-clicking on the backpack in that scenario gets the tank upgrade onto your cursor but you cannot put it down. 

This leads into the other bug that can be seen in my video. I think this may actually be the same bug just played out in a slightly different fashion. Having a battery upgrade and a tank upgrade in the same backpack prevents you from moving buckets around interface. You can pick them up but not place them back down again.

**To Reproduce**

1. Open backpack
2. Put tank upgrade in first slot (I also got this to work with the battery upgrade but that one seems less consistent.)
3. Shift click to remove the tank upgrade
4. Inventory appears as seen below.

**Expected behavior**
Tank upgrade removed without issue.

**Screenshots**
https://youtu.be/ThRd8xA3Qfw
![image](https://user-images.githubusercontent.com/22565111/235276808-b4b3ca4d-bf3b-4446-969a-d9b42e1e0ad3.png)


**Versions**
1.19.2-43.2.8/forge

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest release
