### ISSUE TITLE
volume controls miss linked

### ISSUE THREAD

**Issue by AceDrago** [P3pp3rF1y/SophisticatedBackpacks#724]
**Describe the bug**
the control to adjust the sound of volume of the jukebox is linked to the weather in the options and not the jukebox / note block volume slider of the minecraft music and sound options.

**To Reproduce**
any jukebox from the backpack and adjust the volume sliders until finding which volume it was that made it softer and quieter.

**Expected behavior**
the volume to control the jukebox from the backpack mod correctly linked to the proper sound slider option and in this case the jukebox / note block slider.

**Screenshots**
N/A

**Versions**
atm8 1.0.15
forge 43.2.6

**Comment by P3pp3rF1y** [comment]
You will need to report this to ATM8, just retested in dev and anyway the disc is played it is always controllable as jukebox sound volume because that's the category under which the sound is played in all these cases (tested playing from a block, in player's hand, on another mobs back). In ATM8 I can't even control the sound when I have backpack with jukebox in my inventory so there's some mod there that changes how sounds are played or under which categories.
