### ISSUE TITLE
Custom Music Disk Compatibility with Jukebox Upgrade

### ISSUE THREAD

**Issue by Frankky001** [P3pp3rF1y/SophisticatedBackpacks#734]
Add the ability to insert custom music discs. Most current custom music discs use the default Minecraft tag but change the sound file and add it to the game. Custom disc creator like the imd disc datapack generator. Currently when a custom disc is inserted it will play the default minecraft song like '11' for example, but when inserted into a normal jukebox the custom sound is played.

**Comment by P3pp3rF1y** [comment]
Could you give me an example of datapack that I could use here. I can see that I am not syncing any item nbt when playing the sound but without any example I have no idea if just syncing nbt will solve it and honestly I don't see how it could change the result, but I am probably missing something because I don't have any example.

**Comment by P3pp3rF1y** [comment]
in 1.21 we now have component based custom discs so this functionality is supported and any custom disc that uses vanill component system will play in sophisticated jukebox
