### ISSUE TITLE
Game crashed when I try to craft via crafting upgrade

### ISSUE THREAD

**Issue by 1cyM1nt000** [P3pp3rF1y/SophisticatedBackpacks#763]
I was crafting an iron leggings, the result showed up but when I try to "shift-click" it to my inventory the game froze for couple seconds and then crashed. Please help.

Crash log:
https://mclo.gs/W6r1UaY

**Comment by 1cyM1nt000** [comment]
Update: It just crash when I try to swap my stuff between containers using shift-click. Dragging or clicking the item to move still fine.

**Comment by P3pp3rF1y** [comment]
I am unable to recreate myself in dev as well as in ATM8 which is really huge modpack so it's likely some mod interaction in yours or issue specifit to that backpack. Could you try the same in a new backpack? and if it still crashes there I will need you to find out minimal set of mods with which it crashes then I can take it from there and figure out what's wrong. Using ATM8 list of mods as those that are not causing your issue is probably safe so that should help.

**Comment by 1cyM1nt000** [comment]
Tried the same thing with every tiers and the game still crashed. I found out that it's because the **smooth swapping** mod that conflicted with your mod. I put all my mods back except smooth swapping and everything works fine:). Hope this helps!

**Comment by P3pp3rF1y** [comment]
ok, then that's actually already reported bug to smooth swapping and something that needs to be fixed on their side. There's already a report over there for this and this appears to be a pretty common bug with smooth swapping for a number of other mods. https://github.com/baguchan/Smooth-Swapping-Forge/issues/5
