### ISSUE TITLE
[Feature request] Change sorting behavior to fill slot where Memory Setting exist

### ISSUE THREAD

**Issue by Renne1002** [P3pp3rF1y/SophisticatedBackpacks#767]
Sort does not move items to slots where memory settings exist.

**Comment by P3pp3rF1y** [comment]
Memory setting slots are excluded from sorting on purpose and adding this kind of functionality is likely pretty involved and when I thought about it in the past I could come up with a case because of which it would be required - I mean if you're shift clicking stuff into backpack it will always automatically go into the memorized slot so only intentionally putting it elsewhere or memorized slot running out of space are the cases that come to my mind for why it would be required and even then you can unmemorize the slot, sort and memorize again. 

So I will need to have a good reason / good flow description that clearly shows this is needed

**Comment by P3pp3rF1y** [comment]
closing given no additional feedback
