### ISSUE TITLE
Backpack empty, Forge, 1.19.2

### ISSUE THREAD

**Issue by ActuallyEasy** [P3pp3rF1y/SophisticatedBackpacks#768]
**Describe the bug**
Hello, unfortunately this bug description will be rather short since nothing really happened.

I was playing on my server for 4 hours straight and over time upgrading my backpack (bought ingame through the mod SimpleShops) from Normal to Diamond. I then added the Crafting, Smelting and Stack Tier 1 Upgrade. My Backpack was completely filled and at 1am I disconnected. Our server does a daily restart, idk if that's important. However, when I logged back on today, my Diamond Backpack was empty. No items, no upgrades. I have 2 other backpacks, theay seemed to be fine. I read something about UUID's in a rather old issue report from 2021 and the UUID's of all backpacks are different.
I did have Iron smelting ongoing when I left, maybe that caused and issue?

**To Reproduce**
I put some seeds into the Diamond Backpack and reconnected, they were still there. I have no idea what caused this, we started playing on our server 2 days ago. I'll cheat the items I had in there and in case it happens again I'll tell about it here.

**Expected behavior**
I expected my Diamond Backpack to have the upgrades and items in it that it had before I left the server

**Versions**
Mod Version: 3.18.44.815
Library Version: 0.5.49.245

**Comment by P3pp3rF1y** [comment]
My guess is that the SimpleShops are selling backpack with preset UUID which is going to be the same for every backpack bought that way. Which then means that such backpack will automatically get deduplicated using logic that's in the SB code, what that does is go through backpacks of all players online at the moment and collect UUIDs, as soon as it hits a backpack with UUID that it has already encountered it sets a new UUID for that backpack which effectively clears its contents.
So what I think happened there is that another player bought the backpack, the logic encountered their backpack first and then found yours and marked with new UUID making it empty. The other player would still have access to all the items that were in the backpack before.
Proper fix for this would be having the simpleshops sell backpack without uuid so that this won't happen again. I am closing this now but In case this is not what's happening for you and you have steps to recreate the issue (that I can use to recreate the issue for myself) let me know
