### ISSUE TITLE
The magnet upgrade becomes glitchy when I exit fullscreen in 1.18.2

### ISSUE THREAD

**Issue by AnasterianSunstrider** [P3pp3rF1y/SophisticatedBackpacks#778]
Whenever i exist fullscreen with f11 the magnet upgrade ignores whether it's tuned off or not, and it will start picking up items without filtering. If I turn fullscreen back on, it works as intended again. 
I am using version 3.18.48.835 of the mod and and forge 40.2.4 but this is issue is not new as I've experienced with earlier versions as well.

**Comment by P3pp3rF1y** [comment]
I am unable to recreate so I will need more info on how exactly to recreate - when I have magnet turned off, an item on the ground and I try switching between full screen and windowed it just stays on the ground. So this is not enough to recreate your issue. Magnet actually has no idea whether player is full screen or not and in fact it can't because it's running on server where there's nothing like player screen. So I am pretty sure this is related to something else - have you perhaps set the toggle upgrade button to f11 as well?

**Comment by P3pp3rF1y** [comment]
any additional info on this?

**Comment by P3pp3rF1y** [comment]
closing as there was no follow up
