### ISSUE TITLE
cant insert chorus fruits into backpacks

### ISSUE THREAD

**Issue by Rene-Dankwart** [P3pp3rF1y/SophisticatedBackpacks#783]
i cant insert chorus fruits into my backpack, im playing on Vault Hunters 3rd Edition version 10.0.0
modversions are:
Sophisticated Backpacks is 1.18.2-3.18.46.821
Sophisticated Core is 1.18.2-0.5.48.244
Forge 40.2.1

**Comment by P3pp3rF1y** [comment]
what's wrong with doing that? it's just an item like any other

**Comment by P3pp3rF1y** [comment]
ahh right, you're saying you can't insert the chorus fruit, for some reason I read that as you can. the reason is that VH has chorus fruit banned from going into backpack in config. I am pretty sure that's to prevent players being confused why they are randomly teleported when it would be eaten by feeding upgrade. Anyway if you want that changed you would need to discuss that on VH discord.

**Comment by Rene-Dankwart** [comment]
ohh alright didnt knew that. thanks for letting me know^^
