### ISSUE TITLE
Buckets Acting Strange with Advanced Pump Upgrade

### ISSUE THREAD

**Issue by GitCat3** [P3pp3rF1y/SophisticatedBackpacks#794]
**Describe the bug**
Whenever I attempt to move a bucket between my backpack and my inventory, it gets stuck once I pick it up and won't let me put the bucket down anywhere, forcing me to close my backpack every time that I pick up a bucket.
I am running the Valhelsia 5 modpack

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Open backpack with bucket in inventory or backpack
2. Click on bucket
3. attempt to move bucket in or out of backpack
4. bucket does not move when you click, and does not let you put it back, making it so the only way to put it down is by closing the backpack tab

**Expected behavior**
Bucket will transfer between backpack and inventory (and vice versa) with no issues

**Screenshots**
https://streamable.com/g8olct

**Versions**
Mod version: 1.19.2-3.18.45.819
Forge version: 43.2.10

**Comment by P3pp3rF1y** [comment]
Looks like it gets broken like this only in combination with battery upgrade. Looking into why that is the case.

**Comment by GitCat3** [comment]
Weird! I wonder why the battery would be the one that messes with it.

**Comment by P3pp3rF1y** [comment]
found it, apparently a copy paste error on my side that has been there since the battery was added which is more than a year now. Anyway this is fixed in the latest version of sophisticatedcore released on curseforge so just update that and you are set (well unless the pack is using outdated version of backpacks / storage which dont' work with that version in that case you would need to update all of these)

**Comment by GitCat3** [comment]
Thanks so much!
