### ISSUE TITLE
NBT data issue

### ISSUE THREAD

**Issue by E3VL** [P3pp3rF1y/SophisticatedBackpacks#833]
**Describe the bug**
Disconnects players right away 
Log says it couldnt load saved data properly
[debug-5.log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/12094747/debug-5.log)

At the end of the debug log, you can see the error.

**To Reproduce**
1. Not sure what caused it in the first place to be honest

Mod Version: 1.19.2-3.18.54.881
Forge version: 43.2.14

**Comment by P3pp3rF1y** [comment]
Not much I can help with here - looks like your server crashed and didn't save backpack data properly because it crashes in vanilla storage code when it just tries to check the format of the data file stored on disc. Only way to fix this is to restore the `sophisticatedbackpacks.dat` file or simply delete it and lose contents of backpacks but allow the logic to actually work.
