### ISSUE TITLE
Bug that makes backpack items disappear when changing its slot in the inventory

### ISSUE THREAD

**Issue by Davi-Prado** [P3pp3rF1y/SophisticatedBackpacks#834]
**Describe the bug**
when I move the backpack from the slot in the inventory and open it in my hand or on my back, the items inside disappear, this bug only occurs on a server

**To Reproduce**
1. open a backpack and store items
2. move the backpack in the player's inventory
3. open the backpack again

**Expected behavior**
Do not disappear the items '-'

**Screenshots**

**Versions**
Mod version 821

**Comment by P3pp3rF1y** [comment]
So this obviously doesn't happen for most if not all the other players otherwise I would have a ton of issues logged for this already. 
A few additional questions:
- is the server updated to have sophisticated backpacks as well?
- how have you got the backpack - crafted vs pulled from creative menu vs got it from quest or something similar?
- when the items disappear like this and you put new items into the same backpack do they disappear again?

**Comment by P3pp3rF1y** [comment]
If you are running this on Magma server which was reported to me by another player they definitely have this issue - see https://git.magmafoundation.org/magmafoundation/Magma/-/issues/600

**Comment by ezetwd** [comment]
I hope this helps you.  I downgraded the latest Magma update (installed a server.jar from days ago) and set auto-update (magma.yml) to false.  Everything works fine again

**Comment by CosmicDerivative** [comment]
I've also experienced this issue as well. It looks like it may be due to the sorting functionality as well. 

For instance, Ill middle click to sort the inventory when the inventory has a maxed out stack upgrade (just one). It'll then fill the slots of the inventory with the first few individual items with multiple stacks before returning to an incomplete view.

**Comment by P3pp3rF1y** [comment]
@NonBinaryJellyFish that's a different issue - that's the sorting mod deleting your stacks, just disable that and use sorting functionality included in sophisticated

**Comment by P3pp3rF1y** [comment]
closing given that the original issue was resolved
