### ISSUE TITLE
Crash on server join after placing backpack with active pump on ground

### ISSUE THREAD

**Issue by APolarBaer** [P3pp3rF1y/SophisticatedBackpacks#837]
i wanted to pump lava into my backpacks tank, and as soon as i placed it on the ground i crashed, logged back in to the server i crashed again, looked in the logs and saw it might be something to do with sodium rubidium so i disabled that and its still crashing but now theres no mention of sodium.
Modpack CRIF2

before disabling rubidium,
[crash-2023-07-26_04.09.22-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/12169787/crash-2023-07-26_04.09.22-client.txt)

trying without rubidium, 
[crash-2023-07-26_04.22.32-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/12169789/crash-2023-07-26_04.22.32-client.txt)

**To Reproduce**
Add pump and tank to backpack,
place backpack with pump active on ground near lava.
crash

**Expected behavior**
i expected lava to be collected into the tank, without crashing

**Screenshots**

**Versions**
MC 1.18.2
Mod 3.18.57.888
Forge 40.2.9
Rubidium 0.5.6

**Comment by P3pp3rF1y** [comment]
Looks like I need to update VH backpacks so that they would be compatible with the change to fluid rendering I did back in May. For now you can fix this by removing vh backpacks from your pack as they only provide different look, once this is fixed there you can readd and it will just work with the backpacks you will have at the moment.

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest sb vh release on cf
