### ISSUE TITLE
Smelter upgrade won't accept input anymore

### ISSUE THREAD

**Issue by vee-moon** [P3pp3rF1y/SophisticatedBackpacks#867]
**Describe the bug**
The smelting upgrade in my backpack suddenly refuses to accept any input. It had been working fine for a good few hours, until partway through smelting a stack of raw iron with coal blocks, the smelting stopped and now i can't put anything into it to smelt, whether it's ore or food or anything else, though it still takes fuel.

**To Reproduce**
I have genuinely no idea how this happened or why. I don't know how to reproduce this bug but it won't go away 

**Expected behavior**
I expected the smelter to keep using the fuel to smelt the iron.

**Versions**
backpacks: 1.20.1-3.18.50.853
core: 1.20.1-0.5.69.322

**List of other mods**
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/147964526/dd70714c-e59d-433d-9de2-cc6c05c731f6)

**EDIT:** closing and relaunching the game fixed the issue but as of yet i don't know how permanent this fix might be

**Comment by P3pp3rF1y** [comment]
from that list of mods I am guessing the culprit is Essential mod as it seems to do something with world and if it in fact reloads it without actually triggering correct events this will happen. Also the other mods are commonly used in modpacks where smelting upgrade works. However the mod doesn't have any public sources so I can't easily dig into this more.
So the only suggestion I have here is try playing without the mod and see if it happens again.
