### ISSUE TITLE
Inventories being deleted

### ISSUE THREAD

**Issue by thebikwirm** [P3pp3rF1y/SophisticatedBackpacks#870]
Player inventories being delete upon restarting a server

Mods used is server side
Has happened while server has crashed, wipes all backpacks

mc version: 16.5
mod version: 3.15.20.755
forge version: 36.2.39

[New Text Document.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/12924828/New.Text.Document.txt)

**Comment by P3pp3rF1y** [comment]
Are they getting regularly deleted for you with every restart? if there was a crash I can't help with that as during crash the save of the data files in general may not get called and there's nothing I can do about that.

**Comment by thebikwirm** [comment]
the normal crash is the java vm crashing, saves are set for 10 min
it has happened a few times to other players on my server and once for me
the data is being saved but its weird that its happening for some but not others?

**Comment by P3pp3rF1y** [comment]
yeah that doesn't sound like usual data not saving in that case you would lose all backpacks. The only potential thing I can think of is that two backpacks somehow happened to have the same UUID assigned (UUID is id that's used to link to backpack's storage where its contents and settings are stored) and because of that one of them was marked as duplicate and got a new UUID assigned and became empty. However the only ways of getting one like that I am aware of involve stuff like duplicating backpack in creative / getting duplicate backpack as result of something like incorrectly setup quest or structure that includes the backpack in a chest and the only "legit" way of getting duplicate I am aware of is loot pinata feature in Apotheosis, but even in that case you would need to intentionally let mob pickup your backpack and kill them until you get duplicate.

So yeah those are cases that could cause duplicates and then emptying of one of the duplicates, but other than that I have no idea how you would lose contents of your backpack without others not losing theirs as well to something like server crash.

Which means I can't do much here without steps to recreate the issue.

**Comment by thebikwirm** [comment]
So I have encountered this issue again, the server has crashed back shows empty in backpack, but in tooltip and memory slots the stuff is still there?

**Comment by thebikwirm** [comment]
https://media.essential.gg/64a1bea4-14b2-4c21-8426-ef526af17c00
https://media.essential.gg/bb9404cd-ee6d-4f3e-81d5-afd80e43f200
https://media.essential.gg/0b43e102-a812-4139-53c4-b2e94b306d00

**Comment by thebikwirm** [comment]
something with the sophistatedbackpacks.dat file getting corrupted/messed up, the data is still in the file its just not reading it for whatever reason?

**Comment by P3pp3rF1y** [comment]
could you share the actual file @thebikwirm ?

**Comment by thebikwirm** [comment]
best way to share file as git doesnt support .dat?
media fire?

**Comment by P3pp3rF1y** [comment]
> best way to share file as git doesnt support .dat? media fire?

you should be able to just attach file in the reply `Paste, drop, or click to add files`

**Comment by thebikwirm** [comment]
nope doesnt allow .dat file types

**Comment by thebikwirm** [comment]
https://mega.nz/file/8ScCwLzC#6PsWqbdCu3pLwWxtl8PdyEhAESPvzqfRI04wJuE0siA

**Comment by P3pp3rF1y** [comment]
the structure seems to be correct in that dat file @thebikwirm but then again if the server crashed it would require a lot of effort parsing over that data figuring out what that may have caused. So it's always best to just revert to backup of the file

**Comment by thebikwirm** [comment]
if it happens again ill send over the file

**Comment by thebikwirm** [comment]
when it did last time I used an nbt editor to read the file and the data for my backpack was still there just the inventory had been wiped

**Comment by thebikwirm** [comment]
I have a busted .dat file
this is a google drive link

https://drive.google.com/file/d/1FCanT74D_E5Urr_urc59yLLiqN895Rv9/view?usp=sharing
thanks

**Comment by P3pp3rF1y** [comment]
> I have a busted .dat file this is a google drive link
> 
> https://drive.google.com/file/d/1FCanT74D_E5Urr_urc59yLLiqN895Rv9/view?usp=sharing thanks

That file is just empty proper structure, not much I can help you with there

**Comment by thebikwirm** [comment]
oh weird
thanks tho

**Comment by P3pp3rF1y** [comment]
closing as there's nothing more I can do here
