### ISSUE TITLE
Backpack crashing me world 

### ISSUE THREAD

**Issue by Klouver-github** [P3pp3rF1y/SophisticatedBackpacks#923]
**Describe the bug**
I load the game, and I have the backpack installed, A few minutes fly by, crashes, so I look into the server crash log and suspected your backpack cause it's not mesh so it's sus

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests/suggestions or comment on existing ones.

**To Reproduce**
1. Load New World with backpack installed
2. enjoy your time
3. keep enjoying your walks like rainbows and lollipops across the land
4. Fall

**Expected behavior**
Minecraft 

**Screenshots**
I can't post my browsing history here so here is my FBI EXTERNAL LINK!
https://paste.gg/p/anonymous/7a23e6f6bd264f97ab85e075117119dd
**Versions**
yippe ki-yay it was a sophisticated backpacks-1.20.1-3.19.1.962.jar

**Comment by P3pp3rF1y** [comment]
So something is causing your server to not have overworld level or is causing it to not exist at some point and this is where server wide data are saved as a standard by vanilla and mods. There's a ton of mods there in your modpack so you will need to figure out which mod that is and very likely report to them so that they fix. Or if you are able to recreate with sophisticated mods only please let me know steps I can use to recreate.

**Comment by NeedsterW** [comment]
This seems to be happening to me as well, although in my case I'm assuming it's an incompatibility with Easy Anvils.

**Comment by P3pp3rF1y** [comment]
Closing this as there's been no follow up with info I could use to debug.
