### ISSUE TITLE
Slashblade item textures dosent show correctly

### ISSUE THREAD

**Issue by RuafuMan-Obs** [P3pp3rF1y/SophisticatedBackpacks#944]
When opend up Sophisticated backpacks/containers,slashblade blades' textures and names will all become the "-Nameless-" type,the texture will only show correctly when cursor pick it up
![issue01](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/33950546/e7fb4403-f25d-402a-a7c2-09bb532fb155)
![issue02](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/33950546/e47b6a0e-6240-4348-8852-8880ca5989a7)
![issue03](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/33950546/bd5e951f-8f47-41d4-9d18-960941e6c964)

**Comment by P3pp3rF1y** [comment]
I guess they have a special code that they insert into vanilla container screen slot rendering as opposed to doing it in regular gyu item rendering code but because sophisticated doesn't use the vanilla container slot rendering this won't work. Hard to say because their code isn't public (at least not for any version after mc 1.13. I suggest you report to them as the fix is very likely on their side (just move the rendering into regular item rendering `renderAndDecorateItem` / `renderGuiItemDecorations`), let me know in case they can see there's an actual issue with Sophisticated rendering, but to be honest I highly doubt that given many years and so many packs where it's used without any issues for all items in those packs.

**Comment by P3pp3rF1y** [comment]
closing given no additional feedback provided
