### ISSUE TITLE
Drop items obtained from pickups and magnet upgrades are not reflected in the statistics.

### ISSUE THREAD

**Issue by TwelveYO21** [P3pp3rF1y/SophisticatedBackpacks#956]
**Describe the bug**
As the title suggests.
Because of this, mods that function based on statistics are not responsive.
EX: Pick Up Notifier / Completionist’s Index

**Versions**
sophisticatedbackpacks-1.20.1-3.19.4.978

**Comment by P3pp3rF1y** [comment]
I am actually not aware of any statistic like that, perhaps completionist's index adds that statistic in its code (I have never played with the mod). 
From the first look at pickup notifier code it looks like they use the same event to count stats that I use to pickup items (even that is fired just before player would pickup item into their inventory) so it looks like they should be using higher event priority so that they count items that any other mod may be picking up here, but I will take a bit closer look at what's happening there to see if there's anything I can even do on my side.

**Comment by TwelveYO21** [comment]
It still doesn't count, after all.

![2024-05-19_11 55 07](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/58351699/d0602838-f28a-462a-8b8c-6948894ca98b)

**Comment by P3pp3rF1y** [comment]
Added the logging of pickup stats in 1.21 version so from there on this should work.

**Comment by dellmas** [comment]
I'm on mc 1.21.1 neoforge. Have your latest backpack mod update. I use pick up notifier mod. Once I upgrade my backpack to pickup items I'm no longer notified on item pickup. I can turn off that upgrade and still get notified, because it's no longer going into the backpack. I run the server and pick up notifier is also on the server with its config to true  with backpack implementation. The dev for pick up notifier fuzs said in discord reply

"the server option was designed years ago, sophisticated backpacks might have changed in the meantime"

What can we do to fix this?

**Comment by P3pp3rF1y** [comment]
> I'm on mc 1.21.1 neoforge. Have your latest backpack mod update. I use pick up notifier mod. Once I upgrade my backpack to pickup items I'm no longer notified on item pickup. I can turn off that upgrade and still get notified, because it's no longer going into the backpack. I run the server and pick up notifier is also on the server with its config to true with backpack implementation. The dev for pick up notifier fuzs said in discord reply
> 
> "the server option was designed years ago, sophisticated backpacks might have changed in the meantime"
> 
> What can we do to fix this?

I have no idea, SB just handles pickup event. It's possible that pickup notifier handles the event with lower priority but I would have to look through pickup notifier code and possibly even debug, but then again the change would have to be on pickup notifier side so this really needs to be solved over there.

**Comment by dellmas** [comment]
![Image](https://github.com/user-attachments/assets/1cb51c83-9c8a-4eba-b75d-0a9838c87dc5)

**Comment by dellmas** [comment]
![Image](https://github.com/user-attachments/assets/315220d5-e62e-45bd-b685-b7f6ec0a1c65)

**Comment by P3pp3rF1y** [comment]
@dellmas not sure what you're trying to say, but chatgpt needs to learn how this works - if that event wasn't triggered SB pickup logic wouldn't trigger because it listens to that event. This is definitely not on my side and needs to be done on pickup notifier side.

**Comment by P3pp3rF1y** [comment]
actually just realized Chatgpt is referring to block pickup so it's right there. But backpack block isn't handling the pickup when you have pickup on your player, block only handles it when it's set down and in that case there's no connection to the player and even if that was I don't think that player should be notified of pickup that a backpack somewhere in the world is doing.

**Comment by dellmas** [comment]
Thank you. I greatly appreciate your input. I'm just trying to figure this out and see what I may can do. I may make a mod to bridge them together and make it work if I can.

**Comment by TwelveYO21** [comment]
Why are having a conversation on a case that is ‘’completed‘’ and ‘’closed‘’?
