### ISSUE TITLE
Backpack color not shown when placed in world

### ISSUE THREAD

**Issue by SephGER** [P3pp3rF1y/SophisticatedBackpacks#963]
**Describe the bug**
If a backpack is dyed and placed in the world it just shows the default brown color. The color is back when it is picked up again and show correctly in the inventory and when worn on the back.

**To Reproduce**
1. Dye backpack
2. Backpack has the right color in inventory and when worn on back
3. Place in world
4. Dyed color is not shown anymore

**Expected behavior**
Keep the right colors when placed in the world

**Versions**
Minecraft Version 1.20.1
Forge Version 47.2.0
Sophisticated Core Version 0.5.89.425 
Sophisticated Backpack Version 3.18.59.909

**Comment by P3pp3rF1y** [comment]
You have some mod in the modpack which breaks the colors. Just from quickly testing in 1.20 pack that I play this is what I can see
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/2079526/6c1b3da9-54b2-42df-8b5e-c31cd3696079)

Or it may be the ancient version of SB you have there or it may be broken forge as I (and many other mod authors) don't really support forge post 47.1.5 due to broken stuff that was getting introduced there. If you want something newer try neoforge instead.

**Comment by P3pp3rF1y** [comment]
Thinking about this a bit more you may just be using older version of Rubidium which has implementation of biome blend which causes missing colors on modded blocks.

**Comment by P3pp3rF1y** [comment]
There was no response so I am going to assume it was caused by Rubidium's biome blend given that backpack tint works for me and many others.

**Comment by SephGER** [comment]
Yes, sorry totally lost track of this problem! Installed the new version of Rubidium and the error is gone!
